In [97]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [98]:
dataset = pd.read_csv('newData.csv')
dataset = dataset.iloc[11:, 1:-1] * 10**5
dataset = dataset - 131904
dataset

last open10  last high10  last low10  last open9  last high9  \
11        -19550.0     -19550.0    -19738.0    -19662.0    -19628.0   
12        -19662.0     -19628.0    -19837.0    -19765.0    -19649.0   
13        -19765.0     -19649.0    -19874.0    -19812.0    -19573.0   
14        -19812.0     -19573.0    -19855.0    -19710.0    -19004.0   
15        -19710.0     -19004.0    -19774.0    -19186.0    -18885.0   
...            ...          ...         ...         ...         ...   
28855     -16376.0     -16300.0    -16447.0    -16340.0    -16235.0   
28856     -16340.0     -16235.0    -16541.0    -16474.0    -16116.0   
28857     -16474.0     -16116.0    -16499.0    -16123.0    -15929.0   
28858     -16123.0     -15929.0    -16124.0    -15943.0    -15891.0   
28859     -15943.0     -15891.0    -15979.0    -15912.0    -15895.0   

       last low9  last open8  last high8  last low8  last open7  ...  \
11      -19837.0    -19765.0    -19649.0   -19874.0    -19812.0  ...   
12      -19874.0    -19812.0    -19573.0   -19855.0    -19710.0  ...   
13      -19855.0    -19710.0    -19004.0   -19774.0    -19186.0  ...   
14      -19774.0    -19186.0    -18885.0   -19247.0    -19106.0  ...   
15      -19247.0    -19106.0    -18900.0   -19132.0    -19012.0  ...   
...          ...         ...         ...        ...         ...  ...   
28855   -16541.0    -16474.0    -16116.0   -16499.0    -16123.0  ...   
28856   -16499.0    -16123.0    -15929.0   -16124.0    -15943.0  ...   
28857   -16124.0    -15943.0    -15891.0   -15979.0    -15912.0  ...   
28858   -15979.0    -15912.0    -15895.0   -16014.0    -16004.0  ...   
28859   -16014.0    -16004.0    -15713.0   -16024.0    -15739.0  ...   

       last open1  last high1  last low1  last open  last high  last low  \
11       -18521.0    -18242.0   -18716.0   -18460.0   -18258.0  -18791.0   
12       -18460.0    -18258.0   -18791.0   -18364.0   -17394.0  -18546.0   
13       -18364.0    -17394.0   -18546.0   -17537.0   -17456.0  -17734.0   
14       -17537.0    -17456.0   -17734.0   -17709.0   -17630.0  -17889.0   
15       -17709.0    -17630.0   -17889.0   -17734.0   -17571.0  -18002.0   
...           ...         ...        ...        ...        ...       ...   
28855    -16022.0    -15880.0   -16057.0   -15925.0   -15903.0  -16022.0   
28856    -15925.0    -15903.0   -16022.0   -15964.0   -15784.0  -15966.0   
28857    -15964.0    -15784.0   -15966.0   -15822.0   -15715.0  -15909.0   
28858    -15822.0    -15715.0   -15909.0   -15871.0   -15780.0  -16012.0   
28859    -15871.0    -15780.0   -16012.0   -15981.0   -15801.0  -16011.0   

          open     high      low    close  
11    -18364.0 -17394.0 -18546.0 -17536.0  
12    -17537.0 -17456.0 -17734.0 -17630.0  
13    -17709.0 -17630.0 -17889.0 -17713.0  
14    -17734.0 -17571.0 -18002.0 -17909.0  
15    -17948.0 -17646.0 -18130.0 -17740.0  
...        ...      ...      ...      ...  
28855 -15964.0 -15784.0 -15966.0 -15822.0  
28856 -15822.0 -15715.0 -15909.0 -15870.0  
28857 -15871.0 -15780.0 -16012.0 -15981.0  
28858 -15981.0 -15801.0 -16011.0 -15951.0  
28859 -15952.0 -15844.0 -15971.0 -15864.0  

[28849 rows x 37 columns]

In [99]:
x = dataset.iloc[:, :34].values
y = dataset.iloc[:,  34].values
from xgboost import XGBRegressor
regressorHigh = XGBRegressor(base_score=0.2, booster='gbtree', gamma=0, learning_rate=0.1, n_estimator=200)
regressorHigh.fit(x, y)
print(x,y)

[20:38:19] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-08de971ced8a8cdc6-1/xgboost/xgboost-ci-windows/src/learner.cc:767: 
Parameters: { "n_estimator" } are not used.

[[-19550. -19550. -19738. ... -18258. -18791. -18364.]
 [-19662. -19628. -19837. ... -17394. -18546. -17537.]
 [-19765. -19649. -19874. ... -17456. -17734. -17709.]
 ...
 [-16474. -16116. -16499. ... -15715. -15909. -15871.]
 [-16123. -15929. -16124. ... -15780. -16012. -15981.]
 [-15943. -15891. -15979. ... -15801. -16011. -15952.]] [-17394. -17456. -17630. ... -15780. -15801. -15844.]


In [100]:
x = dataset.iloc[:, :35].values
y = dataset.iloc[:,  35].values
from xgboost import XGBRegressor
regressorLow = XGBRegressor(base_score=0.2, booster='gbtree', gamma=0, learning_rate=0.1, n_estimator=200)
regressorLow.fit(x, y)
print(x,y)

[20:38:22] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-08de971ced8a8cdc6-1/xgboost/xgboost-ci-windows/src/learner.cc:767: 
Parameters: { "n_estimator" } are not used.

[[-19550. -19550. -19738. ... -18791. -18364. -17394.]
 [-19662. -19628. -19837. ... -18546. -17537. -17456.]
 [-19765. -19649. -19874. ... -17734. -17709. -17630.]
 ...
 [-16474. -16116. -16499. ... -15909. -15871. -15780.]
 [-16123. -15929. -16124. ... -16012. -15981. -15801.]
 [-15943. -15891. -15979. ... -16011. -15952. -15844.]] [-18546. -17734. -17889. ... -16012. -16011. -15971.]


In [101]:
x = dataset.iloc[:, :36].values
y = dataset.iloc[:,  36].values
from xgboost import XGBRegressor
regressorClose = XGBRegressor(base_score=0.2, booster='gbtree', gamma=0, learning_rate=0.1, n_estimator=200)
regressorClose.fit(x, y)
print(x,y)

[20:38:25] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-08de971ced8a8cdc6-1/xgboost/xgboost-ci-windows/src/learner.cc:767: 
Parameters: { "n_estimator" } are not used.

[[-19550. -19550. -19738. ... -18364. -17394. -18546.]
 [-19662. -19628. -19837. ... -17537. -17456. -17734.]
 [-19765. -19649. -19874. ... -17709. -17630. -17889.]
 ...
 [-16474. -16116. -16499. ... -15871. -15780. -16012.]
 [-16123. -15929. -16124. ... -15981. -15801. -16011.]
 [-15943. -15891. -15979. ... -15952. -15844. -15971.]] [-17536. -17630. -17713. ... -15981. -15951. -15864.]


In [102]:
testSet = pd.read_csv("newData.csv")
testSet = testSet.iloc[11:, :]
openVal = testSet.iloc[:, 34]
closeVal = testSet.iloc[:, 37]
openVal = openVal * 10**5
closeVal = closeVal * 10**5
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[113540. 114367. 114195. ... 116033. 115923. 115952.]
[114368. 114274. 114191. ... 115923. 115953. 116040.]
[1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 

In [103]:
x = dataset.iloc[:, :36].values
from xgboost import XGBClassifier
classifierAscending = XGBClassifier()
classifierAscending.fit(x, test)
print(x)

[[-19550. -19550. -19738. ... -18364. -17394. -18546.]
 [-19662. -19628. -19837. ... -17537. -17456. -17734.]
 [-19765. -19649. -19874. ... -17709. -17630. -17889.]
 ...
 [-16474. -16116. -16499. ... -15871. -15780. -16012.]
 [-16123. -15929. -16124. ... -15981. -15801. -16011.]
 [-15943. -15891. -15979. ... -15952. -15844. -15971.]]


In [104]:
testSet = pd.read_csv('Test.csv')
print(testSet.shape)
testSet = testSet.iloc[11:, 1:35] * 10**5
testSet = testSet - 131904
testSet

(35, 38)


last open10  last high10  last low10  last open9  last high9  last low9  \
11     -21830.0     -21688.0    -21932.0    -21717.0    -21535.0   -21719.0   
12     -21717.0     -21535.0    -21719.0    -21542.0    -21542.0   -21699.0   
13     -21542.0     -21542.0    -21699.0    -21682.0    -21184.0   -21768.0   
14     -21682.0     -21184.0    -21768.0    -21321.0    -20569.0   -21341.0   
15     -21321.0     -20569.0    -21341.0    -20585.0    -20500.0   -20658.0   
16     -20585.0     -20500.0    -20658.0    -20653.0    -20453.0   -20653.0   
17     -20653.0     -20453.0    -20653.0    -20523.0    -20416.0   -20539.0   
18     -20523.0     -20416.0    -20539.0    -20493.0    -20203.0   -20608.0   
19     -20493.0     -20203.0    -20608.0    -20294.0    -20011.0   -20352.0   
20     -20294.0     -20011.0    -20352.0    -20105.0    -19815.0   -20141.0   
21     -20105.0     -19815.0    -20141.0    -19846.0    -19625.0   -19881.0   
22     -19846.0     -19625.0    -19881.0    -19647.0    -19608.0   -19876.0   
23     -19647.0     -19608.0    -19876.0    -19677.0    -19475.0   -19682.0   
24     -19677.0     -19475.0    -19682.0    -19572.0    -19546.0   -19861.0   
25     -19572.0     -19546.0    -19861.0    -19591.0    -19454.0   -19805.0   
26     -19591.0     -19454.0    -19805.0    -19646.0    -19460.0   -19754.0   
27     -19646.0     -19460.0    -19754.0    -19505.0    -19505.0   -19639.0   
28     -19505.0     -19505.0    -19639.0    -19616.0    -19559.0   -19709.0   
29     -19616.0     -19559.0    -19709.0    -19658.0    -19620.0   -19759.0   
30     -19658.0     -19620.0    -19759.0    -19634.0    -19416.0   -19683.0   
31     -19634.0     -19416.0    -19683.0    -19524.0    -19454.0   -19695.0   
32     -19524.0     -19454.0    -19695.0    -19548.0    -19521.0   -19871.0   
33     -19548.0     -19521.0    -19871.0    -19574.0    -19443.0   -19590.0   
34     -19574.0     -19443.0    -19590.0    -19590.0    -19440.0   -19596.0   

    last open8  last high8  last low8  last open7  ...  last open2  \
11    -21542.0    -21542.0   -21699.0    -21682.0  ...    -20493.0   
12    -21682.0    -21184.0   -21768.0    -21321.0  ...    -20294.0   
13    -21321.0    -20569.0   -21341.0    -20585.0  ...    -20105.0   
14    -20585.0    -20500.0   -20658.0    -20653.0  ...    -19846.0   
15    -20653.0    -20453.0   -20653.0    -20523.0  ...    -19647.0   
16    -20523.0    -20416.0   -20539.0    -20493.0  ...    -19677.0   
17    -20493.0    -20203.0   -20608.0    -20294.0  ...    -19572.0   
18    -20294.0    -20011.0   -20352.0    -20105.0  ...    -19591.0   
19    -20105.0    -19815.0   -20141.0    -19846.0  ...    -19646.0   
20    -19846.0    -19625.0   -19881.0    -19647.0  ...    -19505.0   
21    -19647.0    -19608.0   -19876.0    -19677.0  ...    -19616.0   
22    -19677.0    -19475.0   -19682.0    -19572.0  ...    -19658.0   
23    -19572.0    -19546.0   -19861.0    -19591.0  ...    -19634.0   
24    -19591.0    -19454.0   -19805.0    -19646.0  ...    -19524.0   
25    -19646.0    -19460.0   -19754.0    -19505.0  ...    -19548.0   
26    -19505.0    -19505.0   -19639.0    -19616.0  ...    -19574.0   
27    -19616.0    -19559.0   -19709.0    -19658.0  ...    -19590.0   
28    -19658.0    -19620.0   -19759.0    -19634.0  ...    -19485.0   
29    -19634.0    -19416.0   -19683.0    -19524.0  ...    -19386.0   
30    -19524.0    -19454.0   -19695.0    -19548.0  ...    -19531.0   
31    -19548.0    -19521.0   -19871.0    -19574.0  ...    -19506.0   
32    -19574.0    -19443.0   -19590.0    -19590.0  ...    -19756.0   
33    -19590.0    -19440.0   -19596.0    -19485.0  ...    -19641.0   
34    -19485.0    -19340.0   -19519.0    -19386.0  ...    -19608.0   

    last high2  last low2  last open1  last high1  last low1  last open  \
11    -20203.0   -20608.0    -20294.0    -20011.0   -20352.0   -20105.0   
12    -20011.0   -20352.0    -20105.0    -19815.0   -20141.0   -19846.0   
13    -19815.0   -20141.0    -19846.0    -19625.0   

In [105]:
yHigh = regressorHigh.predict(testSet.values)
yHigh = yHigh.reshape(len(yHigh), 1)

[[-19735.77 ]
 [-19480.424]
 [-19580.271]
 [-19354.908]
 [-19432.814]
 [-19404.766]
 [-19339.553]
 [-19496.184]
 [-19471.297]
 [-19466.408]
 [-19337.863]
 [-19436.006]
 [-19490.47 ]
 [-19474.836]
 [-19353.717]
 [-19241.46 ]
 [-19375.719]
 [-19283.287]
 [-19570.662]
 [-19485.777]
 [-19500.43 ]
 [-19578.53 ]
 [-19488.455]
 [-19604.201]]


In [106]:
testSet = pd.read_csv('Test.csv')
print(testSet.shape)
testSet = testSet.iloc[11:, 1:35] * 10**5 - 131904
print(testSet.shape)
testSet.insert(34, 'high', yHigh)
testSet

(35, 38)
(24, 34)


last open10  last high10  last low10  last open9  last high9  last low9  \
11     -21830.0     -21688.0    -21932.0    -21717.0    -21535.0   -21719.0   
12     -21717.0     -21535.0    -21719.0    -21542.0    -21542.0   -21699.0   
13     -21542.0     -21542.0    -21699.0    -21682.0    -21184.0   -21768.0   
14     -21682.0     -21184.0    -21768.0    -21321.0    -20569.0   -21341.0   
15     -21321.0     -20569.0    -21341.0    -20585.0    -20500.0   -20658.0   
16     -20585.0     -20500.0    -20658.0    -20653.0    -20453.0   -20653.0   
17     -20653.0     -20453.0    -20653.0    -20523.0    -20416.0   -20539.0   
18     -20523.0     -20416.0    -20539.0    -20493.0    -20203.0   -20608.0   
19     -20493.0     -20203.0    -20608.0    -20294.0    -20011.0   -20352.0   
20     -20294.0     -20011.0    -20352.0    -20105.0    -19815.0   -20141.0   
21     -20105.0     -19815.0    -20141.0    -19846.0    -19625.0   -19881.0   
22     -19846.0     -19625.0    -19881.0    -19647.0    -19608.0   -19876.0   
23     -19647.0     -19608.0    -19876.0    -19677.0    -19475.0   -19682.0   
24     -19677.0     -19475.0    -19682.0    -19572.0    -19546.0   -19861.0   
25     -19572.0     -19546.0    -19861.0    -19591.0    -19454.0   -19805.0   
26     -19591.0     -19454.0    -19805.0    -19646.0    -19460.0   -19754.0   
27     -19646.0     -19460.0    -19754.0    -19505.0    -19505.0   -19639.0   
28     -19505.0     -19505.0    -19639.0    -19616.0    -19559.0   -19709.0   
29     -19616.0     -19559.0    -19709.0    -19658.0    -19620.0   -19759.0   
30     -19658.0     -19620.0    -19759.0    -19634.0    -19416.0   -19683.0   
31     -19634.0     -19416.0    -19683.0    -19524.0    -19454.0   -19695.0   
32     -19524.0     -19454.0    -19695.0    -19548.0    -19521.0   -19871.0   
33     -19548.0     -19521.0    -19871.0    -19574.0    -19443.0   -19590.0   
34     -19574.0     -19443.0    -19590.0    -19590.0    -19440.0   -19596.0   

    last open8  last high8  last low8  last open7  ...  last high2  last low2  \
11    -21542.0    -21542.0   -21699.0    -21682.0  ...    -20203.0   -20608.0   
12    -21682.0    -21184.0   -21768.0    -21321.0  ...    -20011.0   -20352.0   
13    -21321.0    -20569.0   -21341.0    -20585.0  ...    -19815.0   -20141.0   
14    -20585.0    -20500.0   -20658.0    -20653.0  ...    -19625.0   -19881.0   
15    -20653.0    -20453.0   -20653.0    -20523.0  ...    -19608.0   -19876.0   
16    -20523.0    -20416.0   -20539.0    -20493.0  ...    -19475.0   -19682.0   
17    -20493.0    -20203.0   -20608.0    -20294.0  ...    -19546.0   -19861.0   
18    -20294.0    -20011.0   -20352.0    -20105.0  ...    -19454.0   -19805.0   
19    -20105.0    -19815.0   -20141.0    -19846.0  ...    -19460.0   -19754.0   
20    -19846.0    -19625.0   -19881.0    -19647.0  ...    -19505.0   -19639.0   
21    -19647.0    -19608.0   -19876.0    -19677.0  ...    -19559.0   -19709.0   
22    -19677.0    -19475.0   -19682.0    -19572.0  ...    -19620.0   -19759.0   
23    -19572.0    -19546.0   -19861.0    -19591.0  ...    -19416.0   -19683.0   
24    -19591.0    -19454.0   -19805.0    -19646.0  ...    -19454.0   -19695.0   
25    -19646.0    -19460.0   -19754.0    -19505.0  ...    -19521.0   -19871.0   
26    -19505.0    -19505.0   -19639.0    -19616.0  ...    -19443.0   -19590.0   
27    -19616.0    -19559.0   -19709.0    -19658.0  ...    -19440.0   -19596.0   
28    -19658.0    -19620.0   -19759.0    -19634.0  ...    -19340.0   -19519.0   
29    -19634.0    -19416.0   -19683.0    -19524.0  ...    -19146.0   -19623.0   
30    -19524.0    -19454.0   -19695.0    -19548.0  ...    -19206.0   -19673.0   
31    -19548.0    -19521.0   -19871.0    -19574.0  ...    -19444.0   -19815.0   
32    -19574.0    -19443.0   -19590.0    -19590.0  ...    -19589.0   -19810.0   
33    -19590.0    -19440.0   -19596.0    -19485.0  ...    -19577.0   -19672.0   
34    -19485.0    -19340.0   -19519.0    -19386.0  ...    -19591.0   -19741.0   

  

In [107]:
testSet = testSet.values
yLow = regressorLow.predict(testSet)
yLow = yLow.reshape(len(yLow), 1)
print(yLow)

[[-19985.285]
 [-19813.146]
 [-19816.746]
 [-19792.516]
 [-19810.672]
 [-19798.793]
 [-19743.182]
 [-19747.854]
 [-19781.922]
 [-19825.76 ]
 [-19712.482]
 [-19740.553]
 [-19797.244]
 [-19742.266]
 [-19609.652]
 [-19455.896]
 [-19700.64 ]
 [-19709.848]
 [-19906.16 ]
 [-19801.445]
 [-19776.334]
 [-19797.686]
 [-19835.336]
 [-19812.662]]


In [108]:
testSet = pd.read_csv('Test.csv')
testSet = testSet.iloc[11:, 1:35] * 10**5 - 131904
testSet.insert(34, 'high', yHigh)
testSet.insert(35, 'low', yLow)
testSet

last open10  last high10  last low10  last open9  last high9  last low9  \
11     -21830.0     -21688.0    -21932.0    -21717.0    -21535.0   -21719.0   
12     -21717.0     -21535.0    -21719.0    -21542.0    -21542.0   -21699.0   
13     -21542.0     -21542.0    -21699.0    -21682.0    -21184.0   -21768.0   
14     -21682.0     -21184.0    -21768.0    -21321.0    -20569.0   -21341.0   
15     -21321.0     -20569.0    -21341.0    -20585.0    -20500.0   -20658.0   
16     -20585.0     -20500.0    -20658.0    -20653.0    -20453.0   -20653.0   
17     -20653.0     -20453.0    -20653.0    -20523.0    -20416.0   -20539.0   
18     -20523.0     -20416.0    -20539.0    -20493.0    -20203.0   -20608.0   
19     -20493.0     -20203.0    -20608.0    -20294.0    -20011.0   -20352.0   
20     -20294.0     -20011.0    -20352.0    -20105.0    -19815.0   -20141.0   
21     -20105.0     -19815.0    -20141.0    -19846.0    -19625.0   -19881.0   
22     -19846.0     -19625.0    -19881.0    -19647.0    -19608.0   -19876.0   
23     -19647.0     -19608.0    -19876.0    -19677.0    -19475.0   -19682.0   
24     -19677.0     -19475.0    -19682.0    -19572.0    -19546.0   -19861.0   
25     -19572.0     -19546.0    -19861.0    -19591.0    -19454.0   -19805.0   
26     -19591.0     -19454.0    -19805.0    -19646.0    -19460.0   -19754.0   
27     -19646.0     -19460.0    -19754.0    -19505.0    -19505.0   -19639.0   
28     -19505.0     -19505.0    -19639.0    -19616.0    -19559.0   -19709.0   
29     -19616.0     -19559.0    -19709.0    -19658.0    -19620.0   -19759.0   
30     -19658.0     -19620.0    -19759.0    -19634.0    -19416.0   -19683.0   
31     -19634.0     -19416.0    -19683.0    -19524.0    -19454.0   -19695.0   
32     -19524.0     -19454.0    -19695.0    -19548.0    -19521.0   -19871.0   
33     -19548.0     -19521.0    -19871.0    -19574.0    -19443.0   -19590.0   
34     -19574.0     -19443.0    -19590.0    -19590.0    -19440.0   -19596.0   

    last open8  last high8  last low8  last open7  ...  last low2  last open1  \
11    -21542.0    -21542.0   -21699.0    -21682.0  ...   -20608.0    -20294.0   
12    -21682.0    -21184.0   -21768.0    -21321.0  ...   -20352.0    -20105.0   
13    -21321.0    -20569.0   -21341.0    -20585.0  ...   -20141.0    -19846.0   
14    -20585.0    -20500.0   -20658.0    -20653.0  ...   -19881.0    -19647.0   
15    -20653.0    -20453.0   -20653.0    -20523.0  ...   -19876.0    -19677.0   
16    -20523.0    -20416.0   -20539.0    -20493.0  ...   -19682.0    -19572.0   
17    -20493.0    -20203.0   -20608.0    -20294.0  ...   -19861.0    -19591.0   
18    -20294.0    -20011.0   -20352.0    -20105.0  ...   -19805.0    -19646.0   
19    -20105.0    -19815.0   -20141.0    -19846.0  ...   -19754.0    -19505.0   
20    -19846.0    -19625.0   -19881.0    -19647.0  ...   -19639.0    -19616.0   
21    -19647.0    -19608.0   -19876.0    -19677.0  ...   -19709.0    -19658.0   
22    -19677.0    -19475.0   -19682.0    -19572.0  ...   -19759.0    -19634.0   
23    -19572.0    -19546.0   -19861.0    -19591.0  ...   -19683.0    -19524.0   
24    -19591.0    -19454.0   -19805.0    -19646.0  ...   -19695.0    -19548.0   
25    -19646.0    -19460.0   -19754.0    -19505.0  ...   -19871.0    -19574.0   
26    -19505.0    -19505.0   -19639.0    -19616.0  ...   -19590.0    -19590.0   
27    -19616.0    -19559.0   -19709.0    -19658.0  ...   -19596.0    -19485.0   
28    -19658.0    -19620.0   -19759.0    -19634.0  ...   -19519.0    -19386.0   
29    -19634.0    -19416.0   -19683.0    -19524.0  ...   -19623.0    -19531.0   
30    -19524.0    -19454.0   -19695.0    -19548.0  ...   -19673.0    -19506.0   
31    -19548.0    -19521.0   -19871.0    -19574.0  ...   -19815.0    -19756.0   
32    -19574.0    -19443.0   -19590.0    -19590.0  ...   -19810.0    -19641.0   
33    -19590.0    -19440.0   -19596.0    -19485.0  ...   -19672.0    -19608.0   
34    -19485.0    -19340.0   -19519.0    -19386.0  ...   -19741.0    -19687.0   

  

In [109]:
testSet = testSet.values
yClose = regressorClose.predict(testSet)
yClose = yClose.reshape(len(yClose), 1)
print(yClose)

[[-19844.094]
 [-19644.754]
 [-19659.86 ]
 [-19547.5  ]
 [-19553.598]
 [-19551.96 ]
 [-19538.797]
 [-19644.754]
 [-19644.754]
 [-19644.754]
 [-19534.611]
 [-19556.473]
 [-19649.266]
 [-19652.14 ]
 [-19446.451]
 [-19300.379]
 [-19553.977]
 [-19534.611]
 [-19752.852]
 [-19644.754]
 [-19649.266]
 [-19659.86 ]
 [-19713.54 ]
 [-19654.996]]


In [110]:
dataset = pd.read_csv("Test.csv")
dataset = dataset.iloc[11:, :]
openVal = dataset.iloc[:, 34]
closeVal = dataset.iloc[:, 37]
openVal = openVal * 10**5
closeVal = closeVal * 10**5
openVal = openVal.values
closeVal = closeVal.values
test = []
print(openVal)
print(closeVal)
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(test)

[112058. 112257. 112227. 112332. 112313. 112258. 112399. 112288. 112246.
 112270. 112380. 112356. 112330. 112314. 112419. 112518. 112373. 112398.
 112148. 112263. 112296. 112217. 112321. 112171.]
[112252. 112227. 112332. 112313. 112258. 112395. 112303. 112246. 112270.
 112380. 112356. 112330. 112314. 112418. 112518. 112369. 112397. 112148.
 112280. 112296. 112218. 112323. 112171. 111825.]
[1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0]


In [111]:
ascending1 = classifierAscending.predict_proba(testSet)
asc1 = classifierAscending.predict(testSet)
print(ascending1)
print(asc1)

[[0.49635917 0.50364083]
 [0.71657467 0.28342533]
 [0.5723351  0.42766488]
 [0.42013717 0.57986283]
 [0.5817225  0.41827753]
 [0.33688664 0.66311336]
 [0.5604782  0.43952182]
 [0.537897   0.46210304]
 [0.29296255 0.70703745]
 [0.71657467 0.28342533]
 [0.42013717 0.57986283]
 [0.42013717 0.57986283]
 [0.8373957  0.16260429]
 [0.64021325 0.35978675]
 [0.42406678 0.5759332 ]
 [0.3966757  0.6033243 ]
 [0.42013717 0.57986283]
 [0.5604782  0.43952182]
 [0.24214995 0.75785005]
 [0.4503038  0.5496962 ]
 [0.537897   0.46210304]
 [0.2572496  0.7427504 ]
 [0.8452114  0.15478858]
 [0.20480406 0.79519594]]
[1 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 1 0 1]


In [112]:
print(np.array([1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0]))
print(np.array(asc1))
print(len(asc1))

[1 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0]
[1 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 1 0 1]
24


In [113]:
testSet = pd.read_csv("newData.csv")
testSet = testSet.iloc[11:, :]
openVal = testSet.iloc[:, 34]
closeVal = testSet.iloc[:, 37]
openVal = openVal * 10**5
closeVal = closeVal * 10**5
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
dataset = pd.read_csv("newData.csv")
dataset = dataset.iloc[11:, :]
x = dataset.iloc[:, 1:35]
x = x * 10**5 - 131904
print(x)
x = x.values
classifierAscending2 = XGBClassifier()
classifierAscending2.fit(x, test)

       last open10  last high10  last low10  last open9  last high9  \
11        -19550.0     -19550.0    -19738.0    -19662.0    -19628.0   
12        -19662.0     -19628.0    -19837.0    -19765.0    -19649.0   
13        -19765.0     -19649.0    -19874.0    -19812.0    -19573.0   
14        -19812.0     -19573.0    -19855.0    -19710.0    -19004.0   
15        -19710.0     -19004.0    -19774.0    -19186.0    -18885.0   
...            ...          ...         ...         ...         ...   
28855     -16376.0     -16300.0    -16447.0    -16340.0    -16235.0   
28856     -16340.0     -16235.0    -16541.0    -16474.0    -16116.0   
28857     -16474.0     -16116.0    -16499.0    -16123.0    -15929.0   
28858     -16123.0     -15929.0    -16124.0    -15943.0    -15891.0   
28859     -15943.0     -15891.0    -15979.0    -15912.0    -15895.0   

       last low9  last open8  last high8  last low8  last open7  ...  \
11      -19837.0    -19765.0    -19649.0   -19874.0    -19812.0  ...   
12 

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [121]:
testSet = pd.read_csv('test.csv')
x = testSet.iloc[11:, 1:35].values * 10**5 - 131904
ascending2 = classifierAscending2.predict_proba(x)
asc2 = classifierAscending2.predict(x)
print(ascending2)
print(asc2)

[[0.48244804 0.51755196]
 [0.5665838  0.4334162 ]
 [0.6462687  0.35373124]
 [0.40367168 0.5963283 ]
 [0.5639782  0.4360218 ]
 [0.660154   0.339846  ]
 [0.5321916  0.46780843]
 [0.48409188 0.5159081 ]
 [0.44289947 0.55710053]
 [0.6350006  0.3649994 ]
 [0.5894124  0.4105876 ]
 [0.53737766 0.46262234]
 [0.4460311  0.5539689 ]
 [0.56381875 0.43618125]
 [0.6814187  0.31858128]
 [0.6814187  0.31858128]
 [0.53737766 0.46262234]
 [0.4824735  0.5175265 ]
 [0.3852175  0.6147825 ]
 [0.584339   0.415661  ]
 [0.4517187  0.5482813 ]
 [0.47437072 0.5256293 ]
 [0.61308885 0.38691112]
 [0.5384263  0.46157375]]
[1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0]


In [122]:
print(np.array(asc2))
print(np.array([1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0]))

[1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0]
[1 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0]


In [123]:
dataset = pd.read_csv("newData.csv")
dataset = dataset.iloc[11:, :] * 10**5 - 131904
x = dataset.iloc[:, 1:35]
y = dataset.iloc[:,   35]
x = x.values
y = y.values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor()
regressorHigh.fit(x, y)
yPredHigh = regressorHigh.predict((x[:, :]))
np.set_printoptions(precision=2)
x = dataset.iloc[:, 1:35]
x = x.values
x = np.concatenate((x, yPredHigh.reshape(len(yPredHigh), 1)), 1)
y = dataset.iloc[:, 36]
y = y.values
y = y.reshape(len(y),1)
regressorLow = XGBRegressor()
regressorLow.fit(x, y)
yPredLow = regressorLow.predict((x[:, :]))
np.set_printoptions(precision=2)
x = dataset.iloc[:, 1:35]
x = x.values
x = np.concatenate((x, yPredHigh.reshape(len(yPredHigh), 1)), 1)
x = np.concatenate((x, yPredLow.reshape(len(yPredLow), 1)), 1)
y = dataset.iloc[:,   37]
y = y.values
y = y.reshape(len(y),1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)
yPredClose = regressorClose.predict((x[:, :]))
np.set_printoptions(precision=2)
x = dataset.iloc[:, 1:35]
x = x.values
x = np.concatenate((x, yPredHigh.reshape(len(yPredHigh), 1)), 1)
x = np.concatenate((x, yPredLow.reshape(len(yPredLow), 1)), 1)
x = np.concatenate((x, yPredClose.reshape(len(yPredClose), 1)), 1)
from xgboost import XGBClassifier
classifierAscending3 = XGBClassifier()
classifierAscending3.fit(x, test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [124]:
testSet = pd.read_csv('Test.csv')
testSet = testSet.iloc[11:, 1:35] * 10**5 - 131904
testSet.insert(34, 'high', yHigh)
testSet.insert(35, 'low', yLow)
testSet.insert(36, 'close', yClose)
ascending3 = classifierAscending3.predict_proba(testSet)
asc3 = classifierAscending3.predict(testSet)
print(ascending3)
print(asc3)

[[0.48 0.52]
 [0.63 0.37]
 [0.58 0.42]
 [0.58 0.42]
 [0.48 0.52]
 [0.45 0.55]
 [0.52 0.48]
 [0.43 0.57]
 [0.45 0.55]
 [0.61 0.39]
 [0.35 0.65]
 [0.42 0.58]
 [0.6  0.4 ]
 [0.6  0.4 ]
 [0.65 0.35]
 [0.45 0.55]
 [0.42 0.58]
 [0.42 0.58]
 [0.53 0.47]
 [0.61 0.39]
 [0.5  0.5 ]
 [0.45 0.55]
 [0.49 0.51]
 [0.45 0.55]]
[1 0 0 0 1 1 0 1 1 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1]


In [125]:
print(np.array(asc3))
print(np.array([1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0]))

[1 0 0 0 1 1 0 1 1 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1]
[1 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0]


In [126]:
ascending = ascending1 + ascending2 + ascending3
print(ascending)

[[1.46 1.54]
 [1.91 1.09]
 [1.79 1.21]
 [1.4  1.6 ]
 [1.62 1.38]
 [1.45 1.55]
 [1.61 1.39]
 [1.46 1.54]
 [1.19 1.81]
 [1.97 1.03]
 [1.36 1.64]
 [1.37 1.63]
 [1.88 1.12]
 [1.8  1.2 ]
 [1.76 1.24]
 [1.52 1.48]
 [1.37 1.63]
 [1.46 1.54]
 [1.16 1.84]
 [1.64 1.36]
 [1.49 1.51]
 [1.18 1.82]
 [1.95 1.05]
 [1.19 1.81]]


In [127]:
predict = []
for i in range(len(ascending)):
    if ascending[i][0] > ascending[i][1]:
        predict.append(0)
    else:
        predict.append(1)
print(predict)

[1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1]


In [128]:
print(np.array(predict))
print(np.array([1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0]))

[1 0 0 1 0 1 0 1 1 0 1 1 0 0 0 0 1 1 1 0 1 1 0 1]
[1 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0]


In [129]:
yHigh += 131904
yLow += 131904
yClose += 131904
yHigh /= 10**5
yLow /= 10**5
yClose /= 10**5

In [130]:
yHigh

array([[1.12],
       [1.12],
       [1.12],
       [1.13],
       [1.12],
       [1.12],
       [1.13],
       [1.12],
       [1.12],
       [1.12],
       [1.13],
       [1.12],
       [1.12],
       [1.12],
       [1.13],
       [1.13],
       [1.13],
       [1.13],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12]], dtype=float32)

In [131]:
yLow

array([[1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12]], dtype=float32)

In [132]:
yClose

array([[1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.13],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12],
       [1.12]], dtype=float32)

In [136]:
temp = pd.read_csv('test.csv')
high = temp.iloc[11:, 35]
high = np.array(high)

In [138]:
ans1 = (np.concatenate((high.reshape(len(high), 1), yHigh.reshape(len(yHigh), 1)), 1))

In [139]:
ans1

array([[1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.13],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.13],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.13],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.13, 1.13],
       [1.13, 1.13],
       [1.13, 1.13],
       [1.12, 1.13],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.12],
       [1.12, 1.12]])