In [192]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [193]:
dataset = pd.read_csv("NewDataset.csv")
dataset = dataset.iloc[11:, :]

In [194]:
x = dataset.iloc[:, 1:46]
y = dataset.iloc[:,   46]
x = x * 10**5
y = y * 10**5
x = x.values
y = y.values
y = y.reshape(len(y),1)
print(x)
print(y)

[[1.12354000e+05 1.12354000e+05 1.12166000e+05 ... 1.13113000e+05
  3.10697398e+10 1.13540000e+05]
 [1.12242000e+05 1.12276000e+05 1.12067000e+05 ... 1.13358000e+05
  3.77614606e+10 1.14367000e+05]
 [1.12139000e+05 1.12255000e+05 1.12030000e+05 ... 1.14170000e+05
  9.34425000e+09 1.14195000e+05]
 ...
 [1.15430000e+05 1.15788000e+05 1.15405000e+05 ... 1.15995000e+05
  1.31496600e+09 1.16033000e+05]
 [1.15781000e+05 1.15975000e+05 1.15780000e+05 ... 1.15892000e+05
  1.49143300e+09 1.15923000e+05]
 [1.15961000e+05 1.16013000e+05 1.15925000e+05 ... 1.15893000e+05
  2.00025300e+09 1.15952000e+05]]
[[114510.]
 [114448.]
 [114274.]
 ...
 [116124.]
 [116103.]
 [116060.]]


In [195]:
from xgboost import XGBRegressor
regressorHigh = XGBRegressor()
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [196]:
x = dataset.iloc[:, 1:47]
y = dataset.iloc[:,   47]
x = x * 10**5
y = y * 10**5
x = x.values
y = y.values
y = y.reshape(len(y),1)
print(x)
print(y)

[[1.12354000e+05 1.12354000e+05 1.12166000e+05 ... 3.10697398e+10
  1.13540000e+05 1.14510000e+05]
 [1.12242000e+05 1.12276000e+05 1.12067000e+05 ... 3.77614606e+10
  1.14367000e+05 1.14448000e+05]
 [1.12139000e+05 1.12255000e+05 1.12030000e+05 ... 9.34425000e+09
  1.14195000e+05 1.14274000e+05]
 ...
 [1.15430000e+05 1.15788000e+05 1.15405000e+05 ... 1.31496600e+09
  1.16033000e+05 1.16124000e+05]
 [1.15781000e+05 1.15975000e+05 1.15780000e+05 ... 1.49143300e+09
  1.15923000e+05 1.16103000e+05]
 [1.15961000e+05 1.16013000e+05 1.15925000e+05 ... 2.00025300e+09
  1.15952000e+05 1.16060000e+05]]
[[113358.]
 [114170.]
 [114015.]
 ...
 [115892.]
 [115893.]
 [115933.]]


In [197]:
from xgboost import XGBRegressor
regressorLow = XGBRegressor()
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [198]:
x = dataset.iloc[:, 1:48]
y = dataset.iloc[:,   49]
x = x * 10**5
y = y * 10**5
x = x.values
y = y.values
y = y.reshape(len(y),1)
print(x)
print(y)

[[112354. 112354. 112166. ... 113540. 114510. 113358.]
 [112242. 112276. 112067. ... 114367. 114448. 114170.]
 [112139. 112255. 112030. ... 114195. 114274. 114015.]
 ...
 [115430. 115788. 115405. ... 116033. 116124. 115892.]
 [115781. 115975. 115780. ... 115923. 116103. 115893.]
 [115961. 116013. 115925. ... 115952. 116060. 115933.]]
[[114368.]
 [114274.]
 [114191.]
 ...
 [115923.]
 [115953.]
 [116040.]]


In [199]:
from xgboost import XGBRegressor
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [200]:
dataset = pd.read_csv("NewDataset.csv")
dataset = dataset.iloc[11:, :]
openVal = dataset.iloc[:, 45]
closeVal = dataset.iloc[:, 49]
openVal = openVal * 10**5
closeVal = closeVal * 10**5
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(test)

[1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 

In [201]:
x = dataset.iloc[:, 1:48]
x *= 10**5
x = x.values

In [202]:
from xgboost import XGBClassifier
classifierAscending = XGBClassifier()
classifierAscending.fit(x, test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [203]:
testSet = pd.read_csv('testSet.csv')
print(testSet)

   last open10  last high10  last low10  last volume10  last open9  \
0      1.11411      1.11701     1.11296          16280      1.1161   

   last high9  last low9  last volume9  last open8  last high8  ...  \
0     1.11893    1.11552         18972     1.11799     1.12089  ...   

   last volume2  last open1  last high1  last low1  last volume1  last open  \
0         23095     1.12399     1.12399    1.12265          4117    1.12288   

   last high  last low  last volume   <OPEN>  
0    1.12345   1.12195         2652  1.12246  

[1 rows x 45 columns]


In [204]:
testSet = testSet.iloc[:, :45]
testSet *= 10**5
testSet = testSet.values
print(testSet)

[[1.11411e+05 1.11701e+05 1.11296e+05 1.62800e+09 1.11610e+05 1.11893e+05
  1.11552e+05 1.89720e+09 1.11799e+05 1.12089e+05 1.11763e+05 2.19990e+09
  1.12058e+05 1.12279e+05 1.12023e+05 7.70800e+08 1.12257e+05 1.12296e+05
  1.12028e+05 4.48000e+08 1.12227e+05 1.12429e+05 1.12222e+05 6.00600e+08
  1.12332e+05 1.12358e+05 1.12043e+05 1.19590e+09 1.12313e+05 1.12450e+05
  1.12099e+05 1.40770e+09 1.12258e+05 1.12444e+05 1.12150e+05 2.30950e+09
  1.12399e+05 1.12399e+05 1.12265e+05 4.11700e+08 1.12288e+05 1.12345e+05
  1.12195e+05 2.65200e+08 1.12246e+05]]


In [205]:
yHigh = regressorHigh.predict(testSet)
print(yHigh) #1.1238 1.12033 1.12355

[112328.19]


In [206]:
df = pd.DataFrame(testSet)
df['high'] = yHigh
print(df)

          0         1         2             3         4         5         6  \
0  111411.0  111701.0  111296.0  1.628000e+09  111610.0  111893.0  111552.0   

              7         8         9  ...        36        37        38  \
0  1.897200e+09  111799.0  112089.0  ...  112399.0  112399.0  112265.0   

            39        40        41        42           43        44  \
0  411700000.0  112288.0  112345.0  112195.0  265200000.0  112246.0   

          high  
0  112328.1875  

[1 rows x 46 columns]


In [207]:
testSet = df.values
yLow = regressorLow.predict(testSet)
print(yLow) # 1.12259

[112182.09]


In [208]:
df = pd.DataFrame(testSet)
df['low'] = yLow
print(df)

          0         1         2             3         4         5         6  \
0  111411.0  111701.0  111296.0  1.628000e+09  111610.0  111893.0  111552.0   

              7         8         9  ...        37        38           39  \
0  1.897200e+09  111799.0  112089.0  ...  112399.0  112265.0  411700000.0   

         40        41        42           43        44           45  \
0  112288.0  112345.0  112195.0  265200000.0  112246.0  112328.1875   

            low  
0  112182.09375  

[1 rows x 47 columns]


In [209]:
testSet = df.values
yClose = regressorClose.predict(testSet)
print(yClose) # 1.12260

[112296.86]


In [210]:
print(classifierAscending.predict(testSet))

[1]
