In [134]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [135]:
dataset = pd.read_csv("4H.csv")
dataset = dataset.iloc[11:, :]*10**5 - 131904
openVal = dataset.iloc[:, 34]
closeVal = dataset.iloc[:, 37]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[-18364. -17537. -17709. ... -14550. -15024. -15015.]
[-17536. -17630. -17713. ... -15024. -15014. -14806.]
[1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 

In [136]:
x = dataset.iloc[:, 1:35].values
y = dataset.iloc[:,   35].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor(n_estimators=1500, max_leaves=0)
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=0,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [137]:
y = dataset.iloc[:, 36].values
y = y.reshape(len(y),1)
predHigh = regressorHigh.predict(x)
x = np.concatenate((x, predHigh.reshape(len(predHigh), 1)), 1)
regressorLow = XGBRegressor(n_estimators=1500, max_leaves=0)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=0,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [138]:
y = dataset.iloc[:, 37].values
y = y.reshape(len(y),1)
predLow = regressorLow.predict(x)
x = np.concatenate((x, predLow.reshape(len(predLow), 1)), 1)
regressorClose = XGBRegressor(n_estimators=1500, max_leaves=0)
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=0,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [139]:
y = test
classifierAscending = XGBClassifier(n_estimators=1500, max_leaves=0)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=0,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=1500, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [140]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
yHigh = regressorHigh.predict(testSet.iloc[:, 1:35].values)
yHigh += 131904
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 35:36] + 131904)/10**5), 1)
tempHigh

array([[1.17317724, 1.17293   ],
       [1.17328191, 1.17327   ],
       [1.17401004, 1.17503   ],
       [1.17694998, 1.17494   ],
       [1.17492902, 1.17479   ],
       [1.17600429, 1.17467   ],
       [1.17496943, 1.17417   ],
       [1.17527056, 1.17383   ],
       [1.17217338, 1.17256   ],
       [1.17278588, 1.17231   ],
       [1.17270231, 1.17305   ],
       [1.17326987, 1.17254   ],
       [1.1731534 , 1.17246   ],
       [1.17085373, 1.17108   ],
       [1.17232263, 1.17099   ],
       [1.17182112, 1.17086   ],
       [1.17143619, 1.17008   ],
       [1.17036223, 1.1699    ],
       [1.17109835, 1.17034   ],
       [1.1697675 , 1.16936   ],
       [1.16890514, 1.17014   ],
       [1.16950679, 1.16894   ],
       [1.16994631, 1.16884   ],
       [1.16876173, 1.16903   ],
       [1.17000175, 1.16881   ],
       [1.16779995, 1.16717   ],
       [1.16505265, 1.16465   ],
       [1.16194367, 1.16053   ],
       [1.1614958 , 1.16038   ],
       [1.16158271, 1.16089   ],
       [1.

In [141]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 35:36] + 131904)/10**5, yHigh)

0.9629829282456785

In [142]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
yLow = regressorLow.predict(testSet.iloc[:, 1:36].values)
yLow += 131904
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 36:37] + 131904)/10**5), 1)
tempLow

array([[1.17006934, 1.17062   ],
       [1.17111659, 1.17113   ],
       [1.17229295, 1.17216   ],
       [1.17251194, 1.1736    ],
       [1.17309952, 1.17377   ],
       [1.17219841, 1.17361   ],
       [1.17335927, 1.17311   ],
       [1.17269897, 1.17068   ],
       [1.17008114, 1.17008   ],
       [1.17048621, 1.17133   ],
       [1.17182183, 1.17171   ],
       [1.17143321, 1.17169   ],
       [1.17117393, 1.16848   ],
       [1.16772723, 1.16894   ],
       [1.16880536, 1.16909   ],
       [1.16857553, 1.16945   ],
       [1.16804588, 1.16862   ],
       [1.16794717, 1.16852   ],
       [1.16702449, 1.16724   ],
       [1.16613042, 1.16728   ],
       [1.16669559, 1.16685   ],
       [1.16737294, 1.16756   ],
       [1.16804063, 1.16803   ],
       [1.16734076, 1.16782   ],
       [1.16726208, 1.16566   ],
       [1.16543376, 1.16402   ],
       [1.16258717, 1.16009   ],
       [1.1596874 , 1.15896   ],
       [1.1594758 , 1.15972   ],
       [1.1592319 , 1.16014   ],
       [1.

In [143]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 36:37] + 131904)/10**5, yLow)

0.9568439096217667

In [144]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
yClose = regressorClose.predict(testSet.iloc[:, 1:37].values)
yClose += 131904
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 37:38] + 131904)/10**5), 1)
tempClose

array([[1.17219043, 1.1721    ],
       [1.17181289, 1.17293   ],
       [1.17429471, 1.17443   ],
       [1.17456627, 1.17392   ],
       [1.17467034, 1.17462   ],
       [1.17476106, 1.17373   ],
       [1.17377627, 1.17362   ],
       [1.17086017, 1.17068   ],
       [1.17206693, 1.17164   ],
       [1.1715498 , 1.17219   ],
       [1.17244267, 1.17174   ],
       [1.1722703 , 1.17226   ],
       [1.16927969, 1.16896   ],
       [1.17051351, 1.17075   ],
       [1.16954589, 1.17022   ],
       [1.17074025, 1.16969   ],
       [1.16916037, 1.1689    ],
       [1.16935825, 1.1699    ],
       [1.16794538, 1.16807   ],
       [1.16753519, 1.16807   ],
       [1.1678921 , 1.16821   ],
       [1.16805255, 1.16838   ],
       [1.16935098, 1.16814   ],
       [1.16891468, 1.16868   ],
       [1.16740346, 1.16639   ],
       [1.16451502, 1.1646    ],
       [1.16235995, 1.16016   ],
       [1.16079915, 1.15985   ],
       [1.1608634 , 1.16037   ],
       [1.16157579, 1.16082   ],
       [1.

In [145]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 37:38] + 131904)/10**5, yClose)

0.9805455129308881

In [146]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
openVal = testSet.iloc[:, 34].values
closeVal = testSet.iloc[:, 37].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1]

In [147]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
yAscending = classifierAscending.predict(testSet.iloc[:, 1:37].values)
yAscending

array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1])

In [148]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[37 17]
 [ 6 40]]


0.77

In [149]:
yAscendingProb = classifierAscending.predict_proba(testSet.iloc[:, 1:37].values)
yAscendingProb

array([[0.00184506, 0.99815494],
       [0.23853034, 0.76146966],
       [0.0693683 , 0.9306317 ],
       [0.6097759 , 0.39022407],
       [0.16008729, 0.8399127 ],
       [0.8890109 , 0.1109891 ],
       [0.07776225, 0.92223775],
       [0.9749002 , 0.02509984],
       [0.09792155, 0.90207845],
       [0.76212424, 0.23787574],
       [0.51959527, 0.4804047 ],
       [0.33676457, 0.6632354 ],
       [0.98022926, 0.01977073],
       [0.09509206, 0.90490794],
       [0.23405993, 0.76594007],
       [0.12950897, 0.870491  ],
       [0.65234506, 0.34765497],
       [0.68783766, 0.31216234],
       [0.9446506 , 0.05534941],
       [0.71074   , 0.28926003],
       [0.31603378, 0.6839662 ],
       [0.441163  , 0.558837  ],
       [0.35736322, 0.6426368 ],
       [0.59220695, 0.40779305],
       [0.869793  , 0.13020702],
       [0.7800887 , 0.21991129],
       [0.8840413 , 0.1159587 ],
       [0.87054163, 0.12945838],
       [0.2191307 , 0.7808693 ],
       [0.04225391, 0.9577461 ],
       [0.