In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
dataset = pd.read_csv("4H.csv")
dataset = dataset.iloc[22:, :]*10**5 - 131904
openVal = dataset.iloc[:, 67]
closeVal = dataset.iloc[:, 70]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[-17568. -17357. -16902. ... -15065. -15089. -15037.]
[-17364. -16878. -16740. ... -15090. -15036. -15265.]
[1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 

In [3]:
x = dataset.iloc[:, 1:68].values
y = dataset.iloc[:,   68].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor()
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [4]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
yHigh = regressorHigh.predict(testSet.iloc[:, 1:68].values)
yHigh += 131904
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 68:69] + 131904)/10**5), 1)
tempHigh

array([[1.167889  , 1.16717   ],
       [1.16509473, 1.16465   ],
       [1.16195071, 1.16053   ],
       [1.16206002, 1.16038   ],
       [1.16206002, 1.16089   ],
       [1.16195071, 1.16099   ],
       [1.16195071, 1.16067   ],
       [1.16195071, 1.15984   ],
       [1.1575135 , 1.15889   ],
       [1.1575135 , 1.15854   ],
       [1.15783763, 1.1582    ],
       [1.15783763, 1.15915   ],
       [1.15783763, 1.16072   ],
       [1.16227472, 1.16075   ],
       [1.16227472, 1.16027   ],
       [1.16227472, 1.16139   ],
       [1.16227472, 1.16041   ],
       [1.16227472, 1.1616    ],
       [1.16227472, 1.16402   ],
       [1.16524303, 1.16396   ],
       [1.16227472, 1.1628    ],
       [1.16227472, 1.16266   ],
       [1.16227472, 1.16136   ],
       [1.16227472, 1.16051   ],
       [1.16227472, 1.16055   ],
       [1.16227472, 1.16133   ],
       [1.16227472, 1.16085   ],
       [1.16227472, 1.16068   ],
       [1.16227472, 1.15968   ],
       [1.16297364, 1.15904   ],
       [1.

In [5]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 68:69] + 131904)/10**5, yHigh)

0.7066333042621549

In [6]:
x = dataset.iloc[:, 1:69].values
y = dataset.iloc[:,   69].values
y = y.reshape(len(y),1)
regressorLow = XGBRegressor(n_estimators=2000)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=2000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [7]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
temp = np.concatenate((testSet.iloc[:, 1:68].values, (yHigh*10**5 - 131904).reshape(len(yHigh), 1)), 1)
temp

array([[-14461.        , -14410.        , -14544.        , ...,
        -15338.        , -15264.        , -15115.10010147],
       [-14510.        , -14425.        , -14527.        , ...,
        -15502.        , -15443.        , -15394.52667618],
       [-14441.        , -14437.        , -14543.        , ...,
        -15895.        , -15889.        , -15708.92925644],
       ...,
       [-16267.        , -16258.        , -16411.        , ...,
        -15909.        , -15871.        , -15676.52817154],
       [-16305.        , -16305.        , -16431.        , ...,
        -16012.        , -15981.        , -15676.52817154],
       [-16409.        , -16294.        , -16425.        , ...,
        -16011.        , -15952.        , -15676.52817154]])

In [8]:
yLow = regressorLow.predict(temp)
yLow += 131904
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 69:70] + 131904)/10**5), 1)
tempLow

array([[1.16554761, 1.16402   ],
       [1.1638931 , 1.16009   ],
       [1.16064107, 1.15896   ],
       [1.16044307, 1.15972   ],
       [1.15946567, 1.16014   ],
       [1.15898669, 1.15917   ],
       [1.16018653, 1.15682   ],
       [1.15724552, 1.15627   ],
       [1.15583575, 1.15632   ],
       [1.15585864, 1.15653   ],
       [1.15584278, 1.15631   ],
       [1.15411067, 1.15748   ],
       [1.15384781, 1.15725   ],
       [1.15976667, 1.15839   ],
       [1.16100371, 1.15919   ],
       [1.16020119, 1.15946   ],
       [1.15913785, 1.15879   ],
       [1.15592277, 1.15958   ],
       [1.15860403, 1.1608    ],
       [1.16194034, 1.16153   ],
       [1.16039419, 1.16163   ],
       [1.16023684, 1.16107   ],
       [1.16013169, 1.15946   ],
       [1.15828061, 1.15901   ],
       [1.15984488, 1.15903   ],
       [1.15975058, 1.15807   ],
       [1.15920389, 1.15938   ],
       [1.16023636, 1.15923   ],
       [1.15868771, 1.15833   ],
       [1.15860283, 1.15512   ],
       [1.

In [9]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 69:70] + 131904)/10**5, yLow)

0.6113793386676571

In [10]:
x = dataset.iloc[:, 1:70].values
y = dataset.iloc[:,   70].values
y = y.reshape(len(y),1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [11]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
temp = np.concatenate((testSet.iloc[:, 1:68].values, (yHigh*10**5 - 131904).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 131904).reshape(len(yLow), 1)), 1)
temp

array([[-14461.        , -14410.        , -14544.        , ...,
        -15264.        , -15115.10010147, -15349.23906708],
       [-14510.        , -14425.        , -14527.        , ...,
        -15443.        , -15394.52667618, -15514.68964005],
       [-14441.        , -14437.        , -14543.        , ...,
        -15889.        , -15708.92925644, -15839.89258194],
       ...,
       [-16267.        , -16258.        , -16411.        , ...,
        -15871.        , -15676.52817154, -15939.36081314],
       [-16305.        , -16305.        , -16431.        , ...,
        -15981.        , -15676.52817154, -16173.17791367],
       [-16409.        , -16294.        , -16425.        , ...,
        -15952.        , -15676.52817154, -16283.99486923]])

In [12]:
yClose = regressorClose.predict(temp)
yClose += 131904
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 70:71] + 131904)/10**5), 1)
tempClose

array([[1.1666348 , 1.1646    ],
       [1.16375542, 1.16016   ],
       [1.16150451, 1.15985   ],
       [1.16150451, 1.16037   ],
       [1.16150451, 1.16082   ],
       [1.16120362, 1.16044   ],
       [1.16150451, 1.15908   ],
       [1.15793383, 1.15708   ],
       [1.15514672, 1.15799   ],
       [1.15479004, 1.15653   ],
       [1.15514672, 1.15807   ],
       [1.15408432, 1.15788   ],
       [1.15408432, 1.16038   ],
       [1.16150451, 1.15971   ],
       [1.16208947, 1.16011   ],
       [1.16150451, 1.16031   ],
       [1.16120362, 1.1596    ],
       [1.15793383, 1.16127   ],
       [1.16120362, 1.16327   ],
       [1.16241825, 1.16192   ],
       [1.16150451, 1.16212   ],
       [1.16150451, 1.16116   ],
       [1.16150451, 1.1595    ],
       [1.16120362, 1.1599    ],
       [1.16150451, 1.16002   ],
       [1.16150451, 1.16053   ],
       [1.16120362, 1.1599    ],
       [1.16150451, 1.15939   ],
       [1.16120362, 1.15848   ],
       [1.16259754, 1.15523   ],
       [1.

In [13]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 70:71] + 131904)/10**5, yClose)

0.25903365506343

In [14]:
y = test
classifierAscending = XGBClassifier(n_estimators=2000)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [15]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
openVal = testSet.iloc[:, 67].values
closeVal = testSet.iloc[:, 70].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1]

In [16]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
temp = np.concatenate((testSet.iloc[:, 1:68].values, (yHigh*10**5 - 131904).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 131904).reshape(len(yLow), 1)), 1)
yAscending = classifierAscending.predict(temp)
yAscending

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0])

In [17]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[18 23]
 [18 16]]


0.4533333333333333

In [18]:
yAscendingProb = classifierAscending.predict_proba(testSet.iloc[:, 1:70].values)
yAscendingProb

array([[0.7429149 , 0.2570851 ],
       [0.98376834, 0.01623168],
       [0.45873892, 0.5412611 ],
       [0.268784  , 0.731216  ],
       [0.01324111, 0.9867589 ],
       [0.8492089 , 0.15079111],
       [0.94102997, 0.05897003],
       [0.93771   , 0.06229   ],
       [0.28017563, 0.7198244 ],
       [0.8227191 , 0.1772809 ],
       [0.10944438, 0.8905556 ],
       [0.14487803, 0.85512197],
       [0.017299  , 0.982701  ],
       [0.86567146, 0.13432856],
       [0.66693914, 0.3330609 ],
       [0.5290258 , 0.47097424],
       [0.8276651 , 0.1723349 ],
       [0.01938093, 0.9806191 ],
       [0.10663122, 0.8933688 ],
       [0.55712354, 0.44287646],
       [0.17804444, 0.82195556],
       [0.34577537, 0.65422463],
       [0.85416603, 0.14583398],
       [0.26005268, 0.7399473 ],
       [0.06265396, 0.93734604],
       [0.08517605, 0.91482395],
       [0.23874766, 0.76125234],
       [0.8922818 , 0.10771822],
       [0.30123687, 0.69876313],
       [0.9078193 , 0.09218071],
       [0.