In [132]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [133]:
dataset = pd.read_csv("NewDataset.csv")
dataset = dataset.iloc[11:, :]

In [134]:
x = dataset.iloc[:, 1:46]
y = dataset.iloc[:,   46]
x = x * 10**5
y = y * 10**5
x = x.values
y = y.values
y = y.reshape(len(y),1)
print(x)
print(y)

[[1.12e+05 1.12e+05 1.12e+05 ... 1.13e+05 3.11e+10 1.14e+05]
 [1.12e+05 1.12e+05 1.12e+05 ... 1.13e+05 3.78e+10 1.14e+05]
 [1.12e+05 1.12e+05 1.12e+05 ... 1.14e+05 9.34e+09 1.14e+05]
 ...
 [1.15e+05 1.16e+05 1.15e+05 ... 1.16e+05 1.31e+09 1.16e+05]
 [1.16e+05 1.16e+05 1.16e+05 ... 1.16e+05 1.49e+09 1.16e+05]
 [1.16e+05 1.16e+05 1.16e+05 ... 1.16e+05 2.00e+09 1.16e+05]]
[[114510.]
 [114448.]
 [114274.]
 ...
 [116124.]
 [116103.]
 [116060.]]


In [135]:
from xgboost import XGBRegressor
regressorHigh = XGBRegressor()
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [136]:
x = dataset.iloc[:, 1:47]
y = dataset.iloc[:,   47]
x = x * 10**5
y = y * 10**5
x = x.values
y = y.values
y = y.reshape(len(y),1)
print(x)
print(y)

[[1.12e+05 1.12e+05 1.12e+05 ... 3.11e+10 1.14e+05 1.15e+05]
 [1.12e+05 1.12e+05 1.12e+05 ... 3.78e+10 1.14e+05 1.14e+05]
 [1.12e+05 1.12e+05 1.12e+05 ... 9.34e+09 1.14e+05 1.14e+05]
 ...
 [1.15e+05 1.16e+05 1.15e+05 ... 1.31e+09 1.16e+05 1.16e+05]
 [1.16e+05 1.16e+05 1.16e+05 ... 1.49e+09 1.16e+05 1.16e+05]
 [1.16e+05 1.16e+05 1.16e+05 ... 2.00e+09 1.16e+05 1.16e+05]]
[[113358.]
 [114170.]
 [114015.]
 ...
 [115892.]
 [115893.]
 [115933.]]


In [137]:
from xgboost import XGBRegressor
regressorLow = XGBRegressor()
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [138]:
x = dataset.iloc[:, 1:48]
y = dataset.iloc[:,   49]
x = x * 10**5
y = y * 10**5
x = x.values
y = y.values
y = y.reshape(len(y),1)
print(x)
print(y)

[[112354. 112354. 112166. ... 113540. 114510. 113358.]
 [112242. 112276. 112067. ... 114367. 114448. 114170.]
 [112139. 112255. 112030. ... 114195. 114274. 114015.]
 ...
 [115430. 115788. 115405. ... 116033. 116124. 115892.]
 [115781. 115975. 115780. ... 115923. 116103. 115893.]
 [115961. 116013. 115925. ... 115952. 116060. 115933.]]
[[114368.]
 [114274.]
 [114191.]
 ...
 [115923.]
 [115953.]
 [116040.]]


In [139]:
from xgboost import XGBRegressor
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [140]:
dataset = pd.read_csv("NewDataset.csv")
dataset = dataset.iloc[11:, :]
openVal = dataset.iloc[:, 45]
closeVal = dataset.iloc[:, 49]
openVal = openVal * 10**5
closeVal = closeVal * 10**5
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(test)

[1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 

In [141]:
x = dataset.iloc[:, 1:48]
x *= 10**5
print(x)
x = x.values

       last open10  last high10  last low10  last volume10  last open9  \
11        112354.0     112354.0    112166.0   9.553310e+09    112242.0   
12        112242.0     112276.0    112067.0   9.377860e+09    112139.0   
13        112139.0     112255.0    112030.0   9.092470e+09    112092.0   
14        112092.0     112331.0    112049.0   9.125470e+09    112194.0   
15        112194.0     112900.0    112130.0   3.080034e+10    112718.0   
...            ...          ...         ...            ...         ...   
28855     115528.0     115604.0    115457.0   1.103024e+09    115564.0   
28856     115564.0     115669.0    115363.0   1.865034e+09    115430.0   
28857     115430.0     115788.0    115405.0   2.359819e+09    115781.0   
28858     115781.0     115975.0    115780.0   1.118868e+09    115961.0   
28859     115961.0     116013.0    115925.0   4.511040e+08    115992.0   

       last high9  last low9  last volume9  last open8  last high8  ...  \
11       112276.0   112067.0  9.3778

In [142]:
from xgboost import XGBClassifier
classifierAscending = XGBClassifier()
classifierAscending.fit(x, test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [143]:
testSet = pd.read_csv('Test.csv')
print(testSet.shape)
testSet = testSet.iloc[11:, 1:46]
print(testSet)

(23, 50)
    last open10  last high10  last low10  last volume10  last open9  \
11      1.10074      1.10216     1.09972         2921.0     1.10187   
12      1.10187      1.10369     1.10185         5539.0     1.10362   
13      1.10362      1.10362     1.10205         9133.0     1.10222   
14      1.10222      1.10720     1.10136        20025.0     1.10583   
15      1.10583      1.11335     1.10563        30965.0     1.11319   
16      1.11319      1.11404     1.11246         6902.0     1.11251   
17      1.11251      1.11451     1.11251         3549.0     1.11381   
18      1.11381      1.11488     1.11365         4948.0     1.11411   
19      1.11411      1.11701     1.11296        16280.0     1.11610   
20      1.11610      1.11893     1.11552        18972.0     1.11799   
21      1.11799      1.12089     1.11763        21999.0     1.12058   
22      1.12058      1.12279     1.12023         7708.0     1.12257   

    last high9  last low9  last volume9  last open8  last high8  ..

In [144]:
testSet = testSet.iloc[:, :45]
testSet *= 10**5
testSet = testSet.values
print(testSet)

[[1.10e+05 1.10e+05 1.10e+05 2.92e+08 1.10e+05 1.10e+05 1.10e+05 5.54e+08
  1.10e+05 1.10e+05 1.10e+05 9.13e+08 1.10e+05 1.11e+05 1.10e+05 2.00e+09
  1.11e+05 1.11e+05 1.11e+05 3.10e+09 1.11e+05 1.11e+05 1.11e+05 6.90e+08
  1.11e+05 1.11e+05 1.11e+05 3.55e+08 1.11e+05 1.11e+05 1.11e+05 4.95e+08
  1.11e+05 1.12e+05 1.11e+05 1.63e+09 1.12e+05 1.12e+05 1.12e+05 1.90e+09
  1.12e+05 1.12e+05 1.12e+05 2.20e+09 1.12e+05]
 [1.10e+05 1.10e+05 1.10e+05 5.54e+08 1.10e+05 1.10e+05 1.10e+05 9.13e+08
  1.10e+05 1.11e+05 1.10e+05 2.00e+09 1.11e+05 1.11e+05 1.11e+05 3.10e+09
  1.11e+05 1.11e+05 1.11e+05 6.90e+08 1.11e+05 1.11e+05 1.11e+05 3.55e+08
  1.11e+05 1.11e+05 1.11e+05 4.95e+08 1.11e+05 1.12e+05 1.11e+05 1.63e+09
  1.12e+05 1.12e+05 1.12e+05 1.90e+09 1.12e+05 1.12e+05 1.12e+05 2.20e+09
  1.12e+05 1.12e+05 1.12e+05 7.71e+08 1.12e+05]
 [1.10e+05 1.10e+05 1.10e+05 9.13e+08 1.10e+05 1.11e+05 1.10e+05 2.00e+09
  1.11e+05 1.11e+05 1.11e+05 3.10e+09 1.11e+05 1.11e+05 1.11e+05 6.90e+08
  1.11e+05 1.11e

In [145]:
yHigh = regressorHigh.predict(testSet)
yHigh = yHigh.reshape(len(yHigh), 1)
print(yHigh) #1.1238 1.12033 1.12355

[[112393.62]
 [112535.15]
 [112443.45]
 [112655.3 ]
 [112528.43]
 [112590.47]
 [112598.08]
 [112545.55]
 [112328.19]
 [112279.73]
 [112619.23]
 [112486.56]]


In [146]:
testSet = pd.read_csv('Test.csv')
print(testSet.shape)
testSet = testSet.iloc[11:, 1:46] * 10**5
print(testSet.shape)
testSet.insert(45, 'high', yHigh)
print(testSet)

(23, 50)
(12, 45)
    last open10  last high10  last low10  last volume10  last open9  \
11     110074.0     110216.0    109972.0   2.921000e+08    110187.0   
12     110187.0     110369.0    110185.0   5.539000e+08    110362.0   
13     110362.0     110362.0    110205.0   9.133000e+08    110222.0   
14     110222.0     110720.0    110136.0   2.002500e+09    110583.0   
15     110583.0     111335.0    110563.0   3.096500e+09    111319.0   
16     111319.0     111404.0    111246.0   6.902000e+08    111251.0   
17     111251.0     111451.0    111251.0   3.549000e+08    111381.0   
18     111381.0     111488.0    111365.0   4.948000e+08    111411.0   
19     111411.0     111701.0    111296.0   1.628000e+09    111610.0   
20     111610.0     111893.0    111552.0   1.897200e+09    111799.0   
21     111799.0     112089.0    111763.0   2.199900e+09    112058.0   
22     112058.0     112279.0    112023.0   7.708000e+08    112257.0   

    last high9  last low9  last volume9  last open8  last 

In [147]:
testSet = testSet.values
yLow = regressorLow.predict(testSet)
yLow = yLow.reshape(len(yLow), 1)
print(yLow) #1.1238 1.12033 1.12355

[[112137.24]
 [112294.09]
 [112311.11]
 [112324.24]
 [112136.91]
 [112193.98]
 [112318.38]
 [112285.03]
 [112182.09]
 [112079.39]
 [112208.76]
 [112224.02]]


In [148]:
testSet = pd.read_csv('Test.csv')
print(testSet.shape)
testSet = testSet.iloc[11:, 1:46] * 10**5
print(testSet.shape)
testSet.insert(45, 'high', yHigh)
testSet.insert(46, 'low', yLow)
print(testSet)

(23, 50)
(12, 45)
    last open10  last high10  last low10  last volume10  last open9  \
11     110074.0     110216.0    109972.0   2.921000e+08    110187.0   
12     110187.0     110369.0    110185.0   5.539000e+08    110362.0   
13     110362.0     110362.0    110205.0   9.133000e+08    110222.0   
14     110222.0     110720.0    110136.0   2.002500e+09    110583.0   
15     110583.0     111335.0    110563.0   3.096500e+09    111319.0   
16     111319.0     111404.0    111246.0   6.902000e+08    111251.0   
17     111251.0     111451.0    111251.0   3.549000e+08    111381.0   
18     111381.0     111488.0    111365.0   4.948000e+08    111411.0   
19     111411.0     111701.0    111296.0   1.628000e+09    111610.0   
20     111610.0     111893.0    111552.0   1.897200e+09    111799.0   
21     111799.0     112089.0    111763.0   2.199900e+09    112058.0   
22     112058.0     112279.0    112023.0   7.708000e+08    112257.0   

    last high9  last low9  last volume9  last open8  last 

In [149]:
testSet = testSet.values
yClose = regressorClose.predict(testSet)
yClose = yClose.reshape(len(yClose), 1)
print(yClose) # 1.12260

[[112284.68]
 [112383.5 ]
 [112400.53]
 [112484.52]
 [112364.57]
 [112396.78]
 [112457.8 ]
 [112409.1 ]
 [112296.86]
 [112221.44]
 [112395.38]
 [112411.21]]


In [150]:
dataset = pd.read_csv("Test.csv")
dataset = dataset.iloc[11:, :]
openVal = dataset.iloc[:, 45]
closeVal = dataset.iloc[:, 48]
openVal = openVal * 10**5
closeVal = closeVal * 10**5
openVal = openVal.values
closeVal = closeVal.values
test = []
print(openVal)
print(closeVal)
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(test)

[112058. 112257. 112227. 112332. 112313. 112258. 112399. 112288. 112246.
 112270. 112380. 112356.]
[112252. 112227. 112332. 112313. 112258. 112395. 112303. 112246. 112270.
 112380. 112356. 112355.]
[1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0]


In [151]:
ascending1 = classifierAscending.predict_proba(testSet)
asc1 = classifierAscending.predict(testSet)
print(ascending1)
print(asc1)

[[0.09 0.91]
 [0.2  0.8 ]
 [0.27 0.73]
 [0.28 0.72]
 [0.35 0.65]
 [0.44 0.56]
 [0.44 0.56]
 [0.2  0.8 ]
 [0.13 0.87]
 [0.48 0.52]
 [0.59 0.41]
 [0.26 0.74]]
[1 1 1 1 1 1 1 1 1 1 0 1]


In [152]:
dataset = pd.read_csv("NewDataset.csv")
dataset = dataset.iloc[11:, :]
openVal = dataset.iloc[:, 45]
closeVal = dataset.iloc[:, 49]
openVal = openVal * 10**5
closeVal = closeVal * 10**5
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(test)

[1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 

In [153]:
dataset = pd.read_csv("NewDataset.csv")
dataset = dataset.iloc[11:, :]
x = dataset.iloc[:, 1:46]
x *= 10**5
print(x)
x = x.values
classifierAscending2 = XGBClassifier()
classifierAscending2.fit(x, test)

       last open10  last high10  last low10  last volume10  last open9  \
11        112354.0     112354.0    112166.0   9.553310e+09    112242.0   
12        112242.0     112276.0    112067.0   9.377860e+09    112139.0   
13        112139.0     112255.0    112030.0   9.092470e+09    112092.0   
14        112092.0     112331.0    112049.0   9.125470e+09    112194.0   
15        112194.0     112900.0    112130.0   3.080034e+10    112718.0   
...            ...          ...         ...            ...         ...   
28855     115528.0     115604.0    115457.0   1.103024e+09    115564.0   
28856     115564.0     115669.0    115363.0   1.865034e+09    115430.0   
28857     115430.0     115788.0    115405.0   2.359819e+09    115781.0   
28858     115781.0     115975.0    115780.0   1.118868e+09    115961.0   
28859     115961.0     116013.0    115925.0   4.511040e+08    115992.0   

       last high9  last low9  last volume9  last open8  last high8  ...  \
11       112276.0   112067.0  9.3778

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [154]:
ascending2 = classifierAscending2.predict_proba(testSet[:, :45])
asc2 = classifierAscending2.predict(testSet[:, :45])
print(ascending2)
print() #[1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0]

[[0.32 0.68]
 [0.74 0.26]
 [0.55 0.45]
 [0.58 0.42]
 [0.7  0.3 ]
 [0.72 0.28]
 [0.41 0.59]
 [0.33 0.67]
 [0.23 0.77]
 [0.48 0.52]
 [0.72 0.28]
 [0.26 0.74]]



In [155]:
dataset = pd.read_csv("NewDataset.csv")
dataset = dataset.iloc[11:, :]
x = dataset.iloc[:, 1:46]
y = dataset.iloc[:,   46]
x = x * 10**5
y = y * 10**5
x = x.values
y = y.values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor()
regressorHigh.fit(x, y)
yPredHigh = regressorHigh.predict((x[:, :]))
np.set_printoptions(precision=2)
x = dataset.iloc[:, 1:46]
x *= 10**5
x = x.values
x = np.concatenate((x, yPredHigh.reshape(len(yPredHigh), 1)), 1)
y = dataset.iloc[:, 47]
y *= 10**5
y = y.values
y = y.reshape(len(y),1)
regressorLow = XGBRegressor()
regressorLow.fit(x, y)
yPredLow = regressorLow.predict((x[:, :]))
np.set_printoptions(precision=2)
x = dataset.iloc[:, 1:46]
x *= 10**5
x = x.values
x = np.concatenate((x, yPredHigh.reshape(len(yPredHigh), 1)), 1)
x = np.concatenate((x, yPredLow.reshape(len(yPredLow), 1)), 1)
y = dataset.iloc[:,   49]
y *= 10**5
y = y.values
y = y.reshape(len(y),1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)
yPredClose = regressorClose.predict((x[:, :]))
np.set_printoptions(precision=2)
x = dataset.iloc[:, 1:46]
x *= 10**5
x = x.values
x = np.concatenate((x, yPredHigh.reshape(len(yPredHigh), 1)), 1)
x = np.concatenate((x, yPredLow.reshape(len(yPredLow), 1)), 1)
x = np.concatenate((x, yPredClose.reshape(len(yPredClose), 1)), 1)
from xgboost import XGBClassifier
classifierAscending3 = XGBClassifier()
classifierAscending3.fit(x, test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [156]:
testSet = pd.read_csv('Test.csv')
testSet = testSet.iloc[11:, 1:46] * 10**5
testSet.insert(45, 'high', yHigh)
testSet.insert(46, 'low', yLow)
testSet.insert(47, 'close', yClose)
ascending3 = classifierAscending3.predict_proba(testSet)
asc3 = classifierAscending3.predict(testSet)
print(ascending3)
print(asc3) #[1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0]

[[0.2  0.8 ]
 [0.59 0.41]
 [0.63 0.37]
 [0.5  0.5 ]
 [0.67 0.33]
 [0.61 0.39]
 [0.58 0.42]
 [0.32 0.68]
 [0.31 0.69]
 [0.78 0.22]
 [0.52 0.48]
 [0.34 0.66]]
[1 0 0 0 0 0 0 1 1 0 0 1]


In [157]:
ascending = ascending1 + ascending2 + ascending3
print(ascending)

[[0.61 2.39]
 [1.53 1.47]
 [1.46 1.54]
 [1.36 1.64]
 [1.72 1.28]
 [1.78 1.22]
 [1.44 1.56]
 [0.85 2.15]
 [0.67 2.33]
 [1.75 1.25]
 [1.83 1.17]
 [0.86 2.14]]


In [158]:
predict = []
for i in range(len(ascending)):
    if ascending[i][0] > ascending[i][1]:
        predict.append(0)
    else:
        predict.append(1)
print(predict) # [1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0]

[1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1]


In [159]:
asc = [1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0]
asc = np.array(asc)
asc1 = np.array(asc1)
asc2 = np.array(asc2)
asc3 = np.array(asc3)
print(asc1)
print(asc2)
print(asc3)
print(np.array(predict))
print(asc)

[1 1 1 1 1 1 1 1 1 1 0 1]
[1 0 0 0 0 0 1 1 1 1 0 1]
[1 0 0 0 0 0 0 1 1 0 0 1]
[1 0 1 1 0 0 1 1 1 0 0 1]
[1 0 1 0 0 1 0 0 1 1 0 0]


In [160]:
#6
#6
#7
#6