In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [35]:
dataset = pd.read_csv("1H.csv")
dataset = dataset.iloc[11:, 1:]*10**5 - 127868.5
openVal = dataset.iloc[:, 33]
closeVal = dataset.iloc[:, 36]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[  6471.5   6421.5   6461.5 ... -19109.5 -19053.5 -19040.5]
[  6411.5   6471.5   6481.5 ... -19053.5 -19041.5 -19001.5]
[0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 

# High

In [36]:
x = dataset.iloc[:, 1:34].values
y = dataset.iloc[:,   34].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor(n_estimators=1000)
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [37]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
yHigh = regressorHigh.predict(testSet.iloc[:, 1:34].values)
yHigh += 127868.5
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 34:35] + 127868.5)/10**5), 1)
tempHigh

array([[1.08896291, 1.08865   ],
       [1.08801031, 1.0888    ],
       [1.08965743, 1.08943   ],
       [1.089396  , 1.08782   ],
       [1.08946526, 1.08792   ],
       [1.08929956, 1.08943   ],
       [1.08978224, 1.08917   ],
       [1.08835351, 1.08736   ],
       [1.08781755, 1.08671   ],
       [1.08825326, 1.08609   ],
       [1.0867579 , 1.08598   ],
       [1.08574653, 1.08536   ],
       [1.08601224, 1.08551   ],
       [1.08594596, 1.08533   ],
       [1.0854212 , 1.08547   ],
       [1.0853672 , 1.08527   ],
       [1.08543622, 1.08554   ],
       [1.08482873, 1.0849    ],
       [1.08478308, 1.085     ],
       [1.08538413, 1.08471   ],
       [1.08492947, 1.084     ],
       [1.08397448, 1.08433   ],
       [1.08450878, 1.08552   ],
       [1.0849998 , 1.08673   ],
       [1.08578253, 1.08555   ],
       [1.08427739, 1.08643   ],
       [1.08662605, 1.08617   ],
       [1.0858289 , 1.08869   ],
       [1.0883373 , 1.08954   ],
       [1.08675027, 1.08739   ],
       [1.

In [38]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 34:35] + 127868.5)/10**5, yHigh)

0.9958227029923009

# Low

In [39]:
x = dataset.iloc[:, 1:35].values
y = dataset.iloc[:,   35].values
y = y.reshape(len(y),1)
regressorLow = XGBRegressor(n_estimators=1000)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [40]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
temp = np.concatenate((testSet.iloc[:, 1:34].values, (yHigh*10**5 - 127868.5).reshape(len(yHigh), 1)), 1)
temp

array([[-19078.5       , -19055.5       , -19118.5       , ...,
        -18789.5       , -19045.5       , -18972.20874405],
       [-19076.5       , -19052.5       , -19101.5       , ...,
        -18926.5       , -19204.5       , -19067.46888733],
       [-19066.5       , -19035.5       , -19075.5       , ...,
        -18911.5       , -19113.5       , -18902.75741196],
       ...,
       [-16438.5       , -16421.5       , -16618.5       , ...,
        -16578.5       , -16639.5       , -16593.92381287],
       [-16588.5       , -16491.5       , -16652.5       , ...,
        -16565.5       , -16627.5       , -16567.12556458],
       [-16585.5       , -16547.5       , -16648.5       , ...,
        -16613.5       , -16676.5       , -16553.83372879]])

In [41]:
yLow = regressorLow.predict(temp)
yLow += 127868.5
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 35:36] + 127868.5)/10**5), 1)
tempLow

array([[1.087309  , 1.08942   ],
       [1.08576155, 1.08957   ],
       [1.0872792 , 1.0895    ],
       [1.08656287, 1.08824   ],
       [1.08761775, 1.09021   ],
       [1.08728147, 1.09014   ],
       [1.08750677, 1.08949   ],
       [1.08493209, 1.0877    ],
       [1.08311427, 1.08672   ],
       [1.08502281, 1.08639   ],
       [1.08552873, 1.08654   ],
       [1.08420098, 1.08567   ],
       [1.0837512 , 1.08556   ],
       [1.08488572, 1.08567   ],
       [1.08455682, 1.0857    ],
       [1.08492064, 1.08562   ],
       [1.08479536, 1.0856    ],
       [1.08320642, 1.08505   ],
       [1.08413124, 1.08531   ],
       [1.0844233 , 1.08471   ],
       [1.0839448 , 1.08437   ],
       [1.08311021, 1.08564   ],
       [1.08402967, 1.08693   ],
       [1.08514214, 1.08755   ],
       [1.08434594, 1.08658   ],
       [1.08330929, 1.08687   ],
       [1.08608353, 1.089     ],
       [1.08609128, 1.08979   ],
       [1.08810937, 1.09007   ],
       [1.08455753, 1.08878   ],
       [1.

In [42]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 35:36] + 127868.5)/10**5, yLow)

0.9752590971183612

# Close

In [43]:
x = dataset.iloc[:, 1:36].values
y = dataset.iloc[:,   36].values
y = y.reshape(len(y),1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [44]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
temp = np.concatenate((testSet.iloc[:, 1:34].values, (yHigh*10**5 - 127868.5).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 127868.5).reshape(len(yLow), 1)), 1)
temp

array([[-19078.5       , -19055.5       , -19118.5       , ...,
        -19045.5       , -18972.20874405, -19137.59971237],
       [-19076.5       , -19052.5       , -19101.5       , ...,
        -19204.5       , -19067.46888733, -19292.34529114],
       [-19066.5       , -19035.5       , -19075.5       , ...,
        -19113.5       , -18902.75741196, -19140.57994461],
       ...,
       [-16438.5       , -16421.5       , -16618.5       , ...,
        -16639.5       , -16593.92381287, -16657.52196884],
       [-16588.5       , -16491.5       , -16652.5       , ...,
        -16627.5       , -16567.12556458, -16697.61205292],
       [-16585.5       , -16547.5       , -16648.5       , ...,
        -16676.5       , -16553.83372879, -16669.84820938]])

In [45]:
yClose = regressorClose.predict(temp)
yClose += 127868.5
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 36:37] + 127868.5)/10**5), 1)
tempClose

array([[1.08815622, 1.08664   ],
       [1.08686733, 1.08755   ],
       [1.08836424, 1.08774   ],
       [1.08823788, 1.08755   ],
       [1.08850443, 1.08757   ],
       [1.08836424, 1.08858   ],
       [1.08882511, 1.08671   ],
       [1.08719742, 1.0865    ],
       [1.08500886, 1.08592   ],
       [1.08546805, 1.08583   ],
       [1.08663642, 1.0851    ],
       [1.08493459, 1.08526   ],
       [1.08492184, 1.08526   ],
       [1.08502698, 1.08499   ],
       [1.08502698, 1.08526   ],
       [1.08502698, 1.0852    ],
       [1.08509159, 1.08463   ],
       [1.08416247, 1.08428   ],
       [1.08450627, 1.08461   ],
       [1.08501339, 1.08399   ],
       [1.08426845, 1.08337   ],
       [1.08363414, 1.08417   ],
       [1.08422768, 1.08529   ],
       [1.08447826, 1.08523   ],
       [1.08482122, 1.08455   ],
       [1.083884  , 1.08602   ],
       [1.08676028, 1.08613   ],
       [1.08600223, 1.08835   ],
       [1.08850443, 1.08585   ],
       [1.08590519, 1.08672   ],
       [1.

In [46]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 36:37] + 127868.5)/10**5, yClose)

0.9938667389303258

# Ascending

In [47]:
x = dataset.iloc[:, 1:37].values
y = test
classifierAscending = XGBClassifier(n_estimators=2000)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [48]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, 1:]*10**5 - 127868.5
openVal = testSet.iloc[:, 33].values
closeVal = testSet.iloc[:, 36].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,


In [49]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, 1:]*10**5 - 127868.5
temp = np.concatenate((testSet.iloc[:, 1:34].values, (yHigh*10**5 - 127868.5).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 127868.5).reshape(len(yLow), 1)), 1)
temp = np.concatenate((temp, (yClose*10**5 - 127868.5).reshape(len(yClose), 1)), 1)
yAscending = classifierAscending.predict(temp)
yAscending

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0])

In [50]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[ 91  39]
 [121  49]]


0.4666666666666667

In [51]:
yAsc = []
for i in range(len(yHigh)):
    if yHigh[i]*10**5 - 127868.5 - openVal[i] < 0:
        yAsc.append(0)
    else:
        yAsc.append(1)
yAsc

[1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,


In [52]:
cm = confusion_matrix(ascending, yAsc)
print(cm)
accuracy_score(ascending, yAsc)

[[ 49  81]
 [ 58 112]]


0.5366666666666666

In [53]:
print(tempClose.shape)

(300, 2)


In [58]:
diffClose = []
for i in range(300):
    diffClose.append(tempClose[i][0] - tempClose[i][1])
diffClose

[0.0015162232971190903,
 -0.000682667541503923,
 0.0006242435073853247,
 0.0006878816604614091,
 0.000934433631897047,
 -0.0002157564926148492,
 0.0021151066207885094,
 0.0006974229812621857,
 -0.0009111403656005823,
 -0.00036194618225104946,
 0.001536424064636277,
 -0.0003254077529906141,
 -0.0003381631469725477,
 3.697944641123385e-05,
 -0.00023302055358875862,
 -0.00017302055358880963,
 0.00046159088134767323,
 -0.00011752632141104336,
 -0.00010372673034675373,
 0.0010233895874023347,
 0.0008984507369995676,
 -0.0005358618927002734,
 -0.0010623188400269434,
 -0.0007517409133910302,
 0.00027122421264658136,
 -0.002135999221801743,
 0.0006302825164794523,
 -0.0023477693557738544,
 0.0026544336318969908,
 -0.00081480571746817,
 0.003575043334960837,
 -0.0015982521438597797,
 -0.001508830146789597,
 -0.0003526675415039815,
 -0.0019378025436400659,
 0.00017267719268798665,
 -0.00036377670288079145,
 -0.000769261817932021,
 -0.001314144859313915,
 0.00010276920318608163,
 0.00079276920318

In [59]:
diff = np.array(diffClose)
diff.mean()

0.0001707520661671976

In [60]:
yAsc = []
for i in range(len(yHigh)):
    if (yHigh[i] - 0.0001707)*10**5 - 127868.5 - openVal[i] < 0:
        yAsc.append(0)
    else:
        yAsc.append(1)
yAsc

[1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,


In [61]:
cm = confusion_matrix(ascending, yAsc)
print(cm)
accuracy_score(ascending, yAsc)

[[60 70]
 [71 99]]


0.53