In [183]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [184]:
dataset = pd.read_csv("4H.csv")
dataset = dataset.iloc[11:, 1:]*10**5 - 131904
openVal = dataset.iloc[:, 33]
closeVal = dataset.iloc[:, 36]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[-18364. -17537. -17709. ... -13882. -13728. -13699.]
[-17536. -17630. -17713. ... -13728. -13700. -13535.]
[1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 

# High

In [185]:
x = dataset.iloc[:, 1:34].values
y = dataset.iloc[:,   34].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor(n_estimators=1000)
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [186]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
yHigh = regressorHigh.predict(testSet.iloc[:, 1:34].values)
yHigh += 131904
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 34:35] + 131904)/10**5), 1)
tempHigh

array([[1.18381631, 1.18368   ],
       [1.18008256, 1.18072   ],
       [1.18227386, 1.18105   ],
       [1.18055403, 1.1803    ],
       [1.18105161, 1.17998   ],
       [1.18071425, 1.18141   ],
       [1.18251765, 1.18383   ],
       [1.18679285, 1.18484   ],
       [1.18518865, 1.18402   ],
       [1.18538213, 1.18451   ],
       [1.18430281, 1.18349   ],
       [1.18425155, 1.18459   ],
       [1.18533456, 1.18472   ],
       [1.18564045, 1.18652   ],
       [1.18721008, 1.1876    ],
       [1.18862832, 1.18823   ],
       [1.18903482, 1.18765   ],
       [1.18991292, 1.18748   ],
       [1.18913078, 1.18916   ],
       [1.19032121, 1.18897   ],
       [1.19073462, 1.18848   ],
       [1.19102967, 1.18786   ],
       [1.18742073, 1.18697   ],
       [1.18649495, 1.18642   ],
       [1.1859628 , 1.18663   ],
       [1.18644309, 1.18715   ],
       [1.18819821, 1.18724   ],
       [1.1877569 , 1.18796   ],
       [1.18793082, 1.18756   ],
       [1.18640316, 1.18765   ],
       [1.

In [187]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 34:35] + 131904)/10**5, yHigh)

0.9881071752513947

# Low

In [188]:
x = dataset.iloc[:, 1:35].values
y = dataset.iloc[:,   35].values
y = y.reshape(len(y),1)
regressorLow = XGBRegressor(n_estimators=1000)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [189]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
temp = np.concatenate((testSet.iloc[:, 1:34].values, (yHigh*10**5 - 131904).reshape(len(yHigh), 1)), 1)
temp

array([[-13896.        , -13888.        , -13980.        , ...,
        -13452.        , -13702.        , -13522.36862564],
       [-13920.        , -13846.        , -13960.        , ...,
        -13524.        , -13937.        , -13895.74404144],
       [-13853.        , -13803.        , -13876.        , ...,
        -13771.        , -13869.        , -13676.61352539],
       ...,
       [-16474.        , -16116.        , -16499.        , ...,
        -15715.        , -15909.        , -15981.31056213],
       [-16123.        , -15929.        , -16124.        , ...,
        -15780.        , -16012.        , -15885.89544678],
       [-15943.        , -15891.        , -15979.        , ...,
        -15801.        , -16011.        , -15903.34768677]])

In [190]:
yLow = regressorLow.predict(temp)
yLow += 131904
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 35:36] + 131904)/10**5), 1)
tempLow

array([[1.18132126, 1.1838    ],
       [1.17776084, 1.18133   ],
       [1.17751646, 1.1812    ],
       [1.17730904, 1.18067   ],
       [1.17803931, 1.18168   ],
       [1.17832005, 1.18398   ],
       [1.17958701, 1.18574   ],
       [1.18195426, 1.18513   ],
       [1.18204498, 1.18464   ],
       [1.18404984, 1.18456   ],
       [1.18375301, 1.18517   ],
       [1.18270946, 1.18559   ],
       [1.18389261, 1.18712   ],
       [1.18398809, 1.18764   ],
       [1.1848712 , 1.1883    ],
       [1.18663013, 1.18846   ],
       [1.18709123, 1.18829   ],
       [1.18739092, 1.19093   ],
       [1.18782377, 1.19051   ],
       [1.18790722, 1.18982   ],
       [1.18779659, 1.18867   ],
       [1.18723309, 1.18802   ],
       [1.18587172, 1.18755   ],
       [1.18608642, 1.18674   ],
       [1.18405724, 1.18714   ],
       [1.18415821, 1.18718   ],
       [1.18533611, 1.18819   ],
       [1.18558216, 1.18854   ],
       [1.18578005, 1.18825   ],
       [1.18538988, 1.18805   ],
       [1.

In [191]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 35:36] + 131904)/10**5, yLow)

0.9153488372363692

# Close

In [192]:
x = dataset.iloc[:, 1:36].values
y = dataset.iloc[:,   36].values
y = y.reshape(len(y),1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [193]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
temp = np.concatenate((testSet.iloc[:, 1:34].values, (yHigh*10**5 - 131904).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 131904).reshape(len(yLow), 1)), 1)
temp

array([[-13896.        , -13888.        , -13980.        , ...,
        -13702.        , -13522.36862564, -13771.87366867],
       [-13920.        , -13846.        , -13960.        , ...,
        -13937.        , -13895.74404144, -14127.91605377],
       [-13853.        , -13803.        , -13876.        , ...,
        -13869.        , -13676.61352539, -14152.35395813],
       ...,
       [-16474.        , -16116.        , -16499.        , ...,
        -15909.        , -15981.31056213, -16078.71647263],
       [-16123.        , -15929.        , -16124.        , ...,
        -16012.        , -15885.89544678, -16138.2376709 ],
       [-15943.        , -15891.        , -15979.        , ...,
        -16011.        , -15903.34768677, -16128.42674637]])

In [194]:
yClose = regressorClose.predict(temp)
yClose += 131904
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 36:37] + 131904)/10**5), 1)
tempClose

array([[1.18375003, 1.17967   ],
       [1.17943871, 1.18035   ],
       [1.18049097, 1.18015   ],
       [1.17918873, 1.17988   ],
       [1.17957497, 1.17938   ],
       [1.17957497, 1.18117   ],
       [1.18117964, 1.18332   ],
       [1.18517888, 1.18378   ],
       [1.18382061, 1.18392   ],
       [1.18452597, 1.18348   ],
       [1.18407035, 1.18344   ],
       [1.18407035, 1.18365   ],
       [1.18443799, 1.18466   ],
       [1.18452597, 1.18645   ],
       [1.18698859, 1.18734   ],
       [1.18770754, 1.18764   ],
       [1.18808341, 1.18715   ],
       [1.18808341, 1.1866    ],
       [1.18808341, 1.18719   ],
       [1.18923402, 1.18752   ],
       [1.18923402, 1.18764   ],
       [1.18923402, 1.18651   ],
       [1.18733728, 1.18605   ],
       [1.18718362, 1.1856    ],
       [1.18458605, 1.18578   ],
       [1.18468451, 1.18685   ],
       [1.18789864, 1.18694   ],
       [1.18722832, 1.18752   ],
       [1.18722832, 1.18599   ],
       [1.18702269, 1.18497   ],
       [1.

In [195]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 36:37] + 131904)/10**5, yClose)

0.9796145395662055

# Ascending

In [196]:
x = dataset.iloc[:, 1:37].values
y = test
classifierAscending = XGBClassifier(n_estimators=2000)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [197]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, 1:]*10**5 - 131904
openVal = testSet.iloc[:, 33].values
closeVal = testSet.iloc[:, 36].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1]

In [198]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, 1:]*10**5 - 131904
temp = np.concatenate((testSet.iloc[:, 1:34].values, (yHigh*10**5 - 131904).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 131904).reshape(len(yLow), 1)), 1)
temp = np.concatenate((temp, (yClose*10**5 - 131904).reshape(len(yClose), 1)), 1)
yAscending = classifierAscending.predict(temp)
yAscending

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0])

In [199]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[80 27]
 [61 32]]


0.56

In [200]:
yAsc = []
for i in range(len(yHigh)):
    if yHigh[i]*10**5 - 131904 - openVal[i] < 0:
        yAsc.append(0)
    else:
        yAsc.append(1)
yAsc

[1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1]

In [201]:
cm = confusion_matrix(ascending, yAsc)
print(cm)
accuracy_score(ascending, yAsc)

[[44 63]
 [29 64]]


0.54