In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
dataset = pd.read_csv("4H.csv")
dataset = dataset.iloc[11:, 1:]*10**5 - 131904
openVal = dataset.iloc[:, 33]
closeVal = dataset.iloc[:, 36]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[-18364. -17537. -17709. ... -13882. -13728. -13699.]
[-17536. -17630. -17713. ... -13728. -13700. -13535.]
[1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 

In [3]:
x = dataset.iloc[:, 1:34].values
y = dataset.iloc[:,   34].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor()
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [4]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
yHigh = regressorHigh.predict(testSet.iloc[:, 1:34].values)
yHigh += 131904
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 34:35] + 131904)/10**5), 1)
tempHigh

array([[1.18411589, 1.18368   ],
       [1.18097556, 1.18072   ],
       [1.1818248 , 1.18105   ],
       [1.18063951, 1.1803    ],
       [1.1807487 , 1.17998   ],
       [1.1807487 , 1.18141   ],
       [1.18209898, 1.18383   ],
       [1.18612373, 1.18484   ],
       [1.18517375, 1.18402   ],
       [1.18463159, 1.18451   ],
       [1.18501186, 1.18349   ],
       [1.18472707, 1.18459   ],
       [1.18519032, 1.18472   ],
       [1.18571472, 1.18652   ],
       [1.18657374, 1.1876    ],
       [1.18928254, 1.18823   ],
       [1.18971682, 1.18765   ],
       [1.18928254, 1.18748   ],
       [1.18928254, 1.18916   ],
       [1.18928254, 1.18897   ],
       [1.18971682, 1.18848   ],
       [1.18971682, 1.18786   ],
       [1.18657374, 1.18697   ],
       [1.18657374, 1.18642   ],
       [1.18657374, 1.18663   ],
       [1.18657374, 1.18715   ],
       [1.18928254, 1.18724   ],
       [1.18928254, 1.18796   ],
       [1.18971682, 1.18756   ],
       [1.18657374, 1.18765   ],
       [1.

In [5]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 34:35] + 131904)/10**5, yHigh)

0.9906262310626688

In [6]:
x = dataset.iloc[:, 1:35].values
y = dataset.iloc[:,   35].values
y = y.reshape(len(y),1)
regressorLow = XGBRegressor()
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [7]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
temp = np.concatenate((testSet.iloc[:, 1:34].values, (yHigh*10**5 - 131904).reshape(len(yHigh), 1)), 1)
temp

array([[-13896.        , -13888.        , -13980.        , ...,
        -13452.        , -13702.        , -13492.41133118],
       [-13920.        , -13846.        , -13960.        , ...,
        -13524.        , -13937.        , -13806.44436264],
       [-13853.        , -13803.        , -13876.        , ...,
        -13771.        , -13869.        , -13721.51966476],
       ...,
       [-16474.        , -16116.        , -16499.        , ...,
        -15715.        , -15909.        , -15925.91400528],
       [-16123.        , -15929.        , -16124.        , ...,
        -15780.        , -16012.        , -15925.91400528],
       [-15943.        , -15891.        , -15979.        , ...,
        -15801.        , -16011.        , -15925.91400528]])

In [8]:
yLow = regressorLow.predict(temp)
yLow += 131904
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 35:36] + 131904)/10**5), 1)
tempLow

array([[1.18137348, 1.1838    ],
       [1.17855239, 1.18133   ],
       [1.17842066, 1.1812    ],
       [1.17846072, 1.18067   ],
       [1.17825949, 1.18168   ],
       [1.17825949, 1.18398   ],
       [1.18017542, 1.18574   ],
       [1.18181956, 1.18513   ],
       [1.1826849 , 1.18464   ],
       [1.1826849 , 1.18456   ],
       [1.18236291, 1.18517   ],
       [1.18220186, 1.18559   ],
       [1.18269455, 1.18712   ],
       [1.18331099, 1.18764   ],
       [1.18568516, 1.1883    ],
       [1.18646801, 1.18846   ],
       [1.18646801, 1.18829   ],
       [1.18646801, 1.19093   ],
       [1.18646801, 1.19051   ],
       [1.18646801, 1.18982   ],
       [1.18646801, 1.18867   ],
       [1.18641496, 1.18802   ],
       [1.18568516, 1.18755   ],
       [1.18568516, 1.18674   ],
       [1.18527102, 1.18714   ],
       [1.18563223, 1.18718   ],
       [1.18641496, 1.18819   ],
       [1.18646801, 1.18854   ],
       [1.18646801, 1.18825   ],
       [1.18568516, 1.18805   ],
       [1.

In [9]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 35:36] + 131904)/10**5, yLow)

0.9023040660928162

In [10]:
x = dataset.iloc[:, 1:36].values
y = dataset.iloc[:,   36].values
y = y.reshape(len(y),1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [11]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 131904
temp = np.concatenate((testSet.iloc[:, 1:34].values, (yHigh*10**5 - 131904).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 131904).reshape(len(yLow), 1)), 1)
temp

array([[-13896.        , -13888.        , -13980.        , ...,
        -13702.        , -13492.41133118, -13766.65230179],
       [-13920.        , -13846.        , -13960.        , ...,
        -13937.        , -13806.44436264, -14048.76108551],
       [-13853.        , -13803.        , -13876.        , ...,
        -13869.        , -13721.51966476, -14061.93371201],
       ...,
       [-16474.        , -16116.        , -16499.        , ...,
        -15909.        , -15925.91400528, -15916.19844818],
       [-16123.        , -15929.        , -16124.        , ...,
        -16012.        , -15925.91400528, -16293.5316124 ],
       [-15943.        , -15891.        , -15979.        , ...,
        -16011.        , -15925.91400528, -16293.5316124 ]])

In [12]:
yClose = regressorClose.predict(temp)
yClose += 131904
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 36:37] + 131904)/10**5), 1)
tempClose

array([[1.18411207, 1.17967   ],
       [1.17985106, 1.18035   ],
       [1.18049097, 1.18015   ],
       [1.17957497, 1.17988   ],
       [1.17957497, 1.17938   ],
       [1.17957497, 1.18117   ],
       [1.18138552, 1.18332   ],
       [1.18424797, 1.18378   ],
       [1.18407035, 1.18392   ],
       [1.18407035, 1.18348   ],
       [1.18407035, 1.18344   ],
       [1.18407035, 1.18365   ],
       [1.18407035, 1.18466   ],
       [1.18449771, 1.18645   ],
       [1.18698859, 1.18734   ],
       [1.18770754, 1.18764   ],
       [1.18770754, 1.18715   ],
       [1.18770754, 1.1866    ],
       [1.18800974, 1.18719   ],
       [1.18770754, 1.18752   ],
       [1.18770754, 1.18764   ],
       [1.18770754, 1.18651   ],
       [1.18702269, 1.18605   ],
       [1.18698859, 1.1856    ],
       [1.18698859, 1.18578   ],
       [1.18698859, 1.18685   ],
       [1.18797553, 1.18694   ],
       [1.18770754, 1.18752   ],
       [1.18770754, 1.18599   ],
       [1.18702269, 1.18497   ],
       [1.

In [13]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 36:37] + 131904)/10**5, yClose)

0.9817122603917374

In [14]:
y = test
classifierAscending = XGBClassifier(n_estimators=2000)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [16]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, 1:]*10**5 - 131904
openVal = testSet.iloc[:, 33].values
closeVal = testSet.iloc[:, 36].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1]

In [17]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, 1:]*10**5 - 131904
temp = np.concatenate((testSet.iloc[:, 1:34].values, (yHigh*10**5 - 131904).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 131904).reshape(len(yLow), 1)), 1)
yAscending = classifierAscending.predict(temp)
yAscending

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0])

In [18]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[85 22]
 [74 19]]


0.52

In [19]:
yAsc = []
for i in range(len(yHigh)):
    if yHigh[i]*10**5 - 131904 - openVal[i] < 0:
        yAsc.append(0)
    else:
        yAsc.append(1)
yAsc

[1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1]

In [20]:
cm = confusion_matrix(ascending, yAsc)
print(cm)
accuracy_score(ascending, yAsc)

[[37 70]
 [22 71]]


0.54