In [51]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [52]:
dataset = pd.read_csv("1D.csv")
dataset = dataset.iloc[11:, :]*10**5 - 127873
openVal = dataset.iloc[:, 34]
closeVal = dataset.iloc[:, 37]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[  8333.   8448.   9324. ... -17691. -17911. -18229.]
[  8449.   9324.   8833. ... -17908. -18228. -18049.]
[1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 

In [53]:
x = dataset.iloc[:, 1:35].values
y = dataset.iloc[:,   35].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor()
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [54]:
x = dataset.iloc[:, 1:36].values
y = dataset.iloc[:, 36].values
y = y.reshape(len(y),1)
regressorLow = XGBRegressor()
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [55]:
x = dataset.iloc[:, 1:37].values
y = dataset.iloc[:, 37].values
y = y.reshape(len(y),1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [56]:
x = dataset.iloc[:, 1:37].values
y = test
classifierAscending = XGBClassifier()
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [57]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yHigh = regressorHigh.predict(testSet.iloc[:, 1:35].values)
yHigh += 127873
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 35:36] + 127873)/10**5), 1)
tempHigh

array([[1.10066652, 1.09981   ],
       [1.09270668, 1.09354   ],
       [1.08986509, 1.08618   ],
       [1.09078646, 1.08908   ],
       [1.09275043, 1.09046   ],
       [1.09164143, 1.08736   ],
       [1.08465886, 1.08479   ],
       [1.08682215, 1.08287   ],
       [1.08190942, 1.08241   ],
       [1.08338308, 1.08313   ],
       [1.08483076, 1.08204   ],
       [1.08483684, 1.08012   ],
       [1.07652032, 1.07556   ],
       [1.07625377, 1.07585   ],
       [1.07474327, 1.07292   ],
       [1.07408559, 1.07434   ],
       [1.07426214, 1.07465   ],
       [1.07659495, 1.07356   ],
       [1.07017612, 1.07684   ],
       [1.08157575, 1.07789   ],
       [1.07467628, 1.07107   ],
       [1.07123899, 1.07224   ],
       [1.07194126, 1.07328   ],
       [1.07054293, 1.07396   ],
       [1.07526684, 1.07869   ],
       [1.0793792 , 1.0785    ],
       [1.0735749 , 1.07515   ],
       [1.07316589, 1.079     ],
       [1.08022594, 1.08234   ],
       [1.08219779, 1.0864    ],
       [1.

In [58]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yLow = regressorLow.predict(testSet.iloc[:, 1:36].values)
yLow += 127873
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 36:37] + 127873)/10**5), 1)
tempLow

array([[1.09560168, 1.09      ],
       [1.08860159, 1.08476   ],
       [1.08420658, 1.08453   ],
       [1.08359611, 1.0848    ],
       [1.0833931 , 1.0855    ],
       [1.08362162, 1.08102   ],
       [1.08135176, 1.07624   ],
       [1.07601249, 1.076     ],
       [1.078318  , 1.08043   ],
       [1.07705927, 1.07955   ],
       [1.07845974, 1.07601   ],
       [1.07658303, 1.07421   ],
       [1.06778157, 1.07073   ],
       [1.06629682, 1.07018   ],
       [1.06640863, 1.07158   ],
       [1.06731117, 1.07054   ],
       [1.06361675, 1.06725   ],
       [1.06773162, 1.06352   ],
       [1.06785893, 1.06617   ],
       [1.071823  , 1.0705    ],
       [1.06747389, 1.06937   ],
       [1.06440544, 1.06744   ],
       [1.0633086 , 1.06669   ],
       [1.06298721, 1.06682   ],
       [1.0652988 , 1.07009   ],
       [1.07023847, 1.07428   ],
       [1.07007849, 1.07431   ],
       [1.07294786, 1.0733    ],
       [1.07394469, 1.07591   ],
       [1.07576883, 1.07739   ],
       [1.

In [59]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yClose = regressorClose.predict(testSet.iloc[:, 1:37].values)
yClose += 127873
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 37:38] + 127873)/10**5), 1)
tempClose

array([[1.09562671, 1.09122   ],
       [1.08879292, 1.08477   ],
       [1.08642888, 1.08527   ],
       [1.08901989, 1.08735   ],
       [1.08933568, 1.08653   ],
       [1.08362782, 1.08378   ],
       [1.08348286, 1.07749   ],
       [1.08500147, 1.08019   ],
       [1.08343363, 1.08218   ],
       [1.08211458, 1.08104   ],
       [1.08001935, 1.07691   ],
       [1.07537401, 1.07555   ],
       [1.07038438, 1.07234   ],
       [1.06989968, 1.07227   ],
       [1.07159865, 1.07214   ],
       [1.07026315, 1.07067   ],
       [1.07076132, 1.07316   ],
       [1.06650043, 1.06933   ],
       [1.07331014, 1.07604   ],
       [1.07290912, 1.07063   ],
       [1.0697571 , 1.06967   ],
       [1.06983542, 1.07113   ],
       [1.07025957, 1.06984   ],
       [1.07025957, 1.07069   ],
       [1.07442188, 1.07818   ],
       [1.07391346, 1.07456   ],
       [1.07193363, 1.07499   ],
       [1.07527673, 1.07622   ],
       [1.08122826, 1.07895   ],
       [1.08293104, 1.08427   ],
       [1.

In [60]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
openVal = testSet.iloc[:, 34].values
closeVal = testSet.iloc[:, 37].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0]

In [61]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yAscending = classifierAscending.predict(testSet.iloc[:, 1:37].values)
yAscending

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1])

In [62]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[24  8]
 [10 20]]


0.7096774193548387

In [63]:
yAscendingProb = classifierAscending.predict_proba(testSet.iloc[:, 1:37].values)
yAscendingProb

array([[0.78495514, 0.21504487],
       [0.7503487 , 0.24965133],
       [0.25843096, 0.74156904],
       [0.24246436, 0.75753564],
       [0.7601149 , 0.23988506],
       [0.6017181 , 0.39828187],
       [0.9007567 , 0.09924328],
       [0.18072999, 0.81927   ],
       [0.32928318, 0.6707168 ],
       [0.862892  , 0.13710801],
       [0.6644486 , 0.33555135],
       [0.24568397, 0.75431603],
       [0.7775148 , 0.2224852 ],
       [0.61911166, 0.3808883 ],
       [0.37505937, 0.62494063],
       [0.5805309 , 0.41946915],
       [0.59007686, 0.40992314],
       [0.88153875, 0.11846124],
       [0.496351  , 0.503649  ],
       [0.7977828 , 0.20221719],
       [0.75782305, 0.24217694],
       [0.8177863 , 0.18221372],
       [0.65159374, 0.34840626],
       [0.49928325, 0.50071675],
       [0.48620164, 0.51379836],
       [0.6823753 , 0.31762472],
       [0.60532624, 0.39467376],
       [0.739709  , 0.260291  ],
       [0.77137065, 0.22862934],
       [0.17695862, 0.8230414 ],
       [0.