In [340]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [341]:
dataset = pd.read_csv("1D.csv")
dataset = dataset.iloc[11:, :]*10**5 - 127873
openVal = dataset.iloc[:, 34]
closeVal = dataset.iloc[:, 37]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[  8333.   8448.   9324. ... -17691. -17911. -18229.]
[  8449.   9324.   8833. ... -17908. -18228. -18049.]
[1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 

In [342]:
x = dataset.iloc[:, 1:35].values
y = dataset.iloc[:,   35].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor(n_estimators=3000)
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=3000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [343]:
y = dataset.iloc[:, 36].values
y = y.reshape(len(y),1)
predHigh = regressorHigh.predict(x)
x = np.concatenate((x, predHigh.reshape(len(predHigh), 1)), 1)
regressorLow = XGBRegressor(n_estimators=1500)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [344]:
y = dataset.iloc[:, 37].values
y = y.reshape(len(y),1)
predLow = regressorLow.predict(x)
x = np.concatenate((x, predLow.reshape(len(predLow), 1)), 1)
regressorClose = XGBRegressor(n_estimators=2000)
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=2000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [345]:
y = test
classifierAscending = XGBClassifier(n_estimators=3000)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=3000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [346]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yHigh = regressorHigh.predict(testSet.iloc[:, 1:35].values)
yHigh += 127873
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 35:36] + 127873)/10**5), 1)
tempHigh

array([[1.10184979, 1.09981   ],
       [1.09180951, 1.09354   ],
       [1.08995783, 1.08618   ],
       [1.0904572 , 1.08908   ],
       [1.09188819, 1.09046   ],
       [1.09144258, 1.08736   ],
       [1.08504498, 1.08479   ],
       [1.08707476, 1.08287   ],
       [1.08194375, 1.08241   ],
       [1.08338511, 1.08313   ],
       [1.08404684, 1.08204   ],
       [1.08578002, 1.08012   ],
       [1.07643723, 1.07556   ],
       [1.07573032, 1.07585   ],
       [1.0743953 , 1.07292   ],
       [1.07322848, 1.07434   ],
       [1.07374763, 1.07465   ],
       [1.07682371, 1.07356   ],
       [1.07046437, 1.07684   ],
       [1.08173358, 1.07789   ],
       [1.07410252, 1.07107   ],
       [1.07094312, 1.07224   ],
       [1.07170641, 1.07328   ],
       [1.07126927, 1.07396   ],
       [1.07649589, 1.07869   ],
       [1.08005238, 1.0785    ],
       [1.07284701, 1.07515   ],
       [1.07247484, 1.079     ],
       [1.07980871, 1.08234   ],
       [1.0819391 , 1.0864    ],
       [1.

In [347]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 35:36] + 127873)/10**5, yHigh)

0.952554195493755

In [348]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yLow = regressorLow.predict(testSet.iloc[:, 1:36].values)
yLow += 127873
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 36:37] + 127873)/10**5), 1)
tempLow

array([[1.09484577, 1.09      ],
       [1.08844376, 1.08476   ],
       [1.08604443, 1.08453   ],
       [1.08247769, 1.0848    ],
       [1.08335006, 1.0855    ],
       [1.08508718, 1.08102   ],
       [1.08052182, 1.07624   ],
       [1.07481825, 1.076     ],
       [1.0788393 , 1.08043   ],
       [1.07885563, 1.07955   ],
       [1.07867146, 1.07601   ],
       [1.07559097, 1.07421   ],
       [1.06746793, 1.07073   ],
       [1.06720734, 1.07018   ],
       [1.06669319, 1.07158   ],
       [1.06787682, 1.07054   ],
       [1.06525481, 1.06725   ],
       [1.06743813, 1.06352   ],
       [1.06791723, 1.06617   ],
       [1.07148433, 1.0705    ],
       [1.0650171 , 1.06937   ],
       [1.0654999 , 1.06744   ],
       [1.064538  , 1.06669   ],
       [1.06546998, 1.06682   ],
       [1.06630421, 1.07009   ],
       [1.06999075, 1.07428   ],
       [1.07124698, 1.07431   ],
       [1.07328069, 1.0733    ],
       [1.07226789, 1.07591   ],
       [1.07757854, 1.07739   ],
       [1.

In [349]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 36:37] + 127873)/10**5, yLow)

0.9564471693208708

In [350]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yClose = regressorClose.predict(testSet.iloc[:, 1:37].values)
yClose += 127873
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 37:38] + 127873)/10**5), 1)
tempClose

array([[1.09410453, 1.09122   ],
       [1.08864558, 1.08477   ],
       [1.08654594, 1.08527   ],
       [1.08855402, 1.08735   ],
       [1.08929896, 1.08653   ],
       [1.08591998, 1.08378   ],
       [1.08146334, 1.07749   ],
       [1.08711183, 1.08019   ],
       [1.08176756, 1.08218   ],
       [1.08234894, 1.08104   ],
       [1.07915533, 1.07691   ],
       [1.07637572, 1.07555   ],
       [1.07010746, 1.07234   ],
       [1.07172453, 1.07227   ],
       [1.0729357 , 1.07214   ],
       [1.07107735, 1.07067   ],
       [1.07021928, 1.07316   ],
       [1.06318951, 1.06933   ],
       [1.07292438, 1.07604   ],
       [1.0727731 , 1.07063   ],
       [1.07018924, 1.06967   ],
       [1.06874621, 1.07113   ],
       [1.07050347, 1.06984   ],
       [1.07106173, 1.07069   ],
       [1.07304645, 1.07818   ],
       [1.07515049, 1.07456   ],
       [1.07428932, 1.07499   ],
       [1.0770849 , 1.07622   ],
       [1.08316374, 1.07895   ],
       [1.08254433, 1.08427   ],
       [1.

In [351]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 37:38] + 127873)/10**5, yClose)

0.9655300412203709

In [352]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
openVal = testSet.iloc[:, 34].values
closeVal = testSet.iloc[:, 37].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0]

In [353]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yAscending = classifierAscending.predict(testSet.iloc[:, 1:37].values)
yAscending

array([0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [354]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[26  6]
 [ 9 21]]


0.7580645161290323

In [355]:
yAscendingProb = classifierAscending.predict_proba(testSet.iloc[:, 1:37].values)
yAscendingProb

array([[9.92249072e-01, 7.75090372e-03],
       [9.97637630e-01, 2.36237980e-03],
       [1.04882300e-01, 8.95117700e-01],
       [1.52098358e-01, 8.47901642e-01],
       [3.12805593e-01, 6.87194407e-01],
       [6.75933182e-01, 3.24066818e-01],
       [9.96583164e-01, 3.41686164e-03],
       [2.89756060e-03, 9.97102439e-01],
       [2.23231316e-03, 9.97767687e-01],
       [9.82177675e-01, 1.78223010e-02],
       [8.83802116e-01, 1.16197884e-01],
       [4.17238474e-03, 9.95827615e-01],
       [9.88067806e-01, 1.19321840e-02],
       [8.44066143e-01, 1.55933872e-01],
       [1.08105958e-01, 8.91894042e-01],
       [8.02142978e-01, 1.97857052e-01],
       [8.70341778e-01, 1.29658192e-01],
       [9.98957574e-01, 1.04241038e-03],
       [7.38504052e-01, 2.61495948e-01],
       [9.97747183e-01, 2.25284602e-03],
       [9.93258953e-01, 6.74102316e-03],
       [9.99425530e-01, 5.74479229e-04],
       [7.62663722e-01, 2.37336308e-01],
       [2.05207527e-01, 7.94792473e-01],
       [3.771169