In [281]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [282]:
dataset = pd.read_csv("1D.csv")
dataset = dataset.iloc[22:, :]*10**5 - 127873
openVal = dataset.iloc[:, 67]
closeVal = dataset.iloc[:, 70]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[  8782.   9014.   9010. ... -17644. -17664. -17691.]
[  9034.   9024.   8196. ... -17711. -17692. -17908.]
[1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 

In [283]:
x = dataset.iloc[:, 35:68].values
y = dataset.iloc[:,   68].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor(n_estimators=3000)
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=3000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [284]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yHigh = regressorHigh.predict(testSet.iloc[:, 35:68].values)
yHigh += 127873
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 68:69] + 127873)/10**5), 1)
tempHigh

array([[1.10156977, 1.10007   ],
       [1.09907138, 1.10068   ],
       [1.10055184, 1.09981   ],
       [1.09313643, 1.09354   ],
       [1.09064889, 1.08618   ],
       [1.09073317, 1.08908   ],
       [1.08959317, 1.09046   ],
       [1.09365249, 1.08736   ],
       [1.08487296, 1.08479   ],
       [1.08703423, 1.08287   ],
       [1.08269572, 1.08241   ],
       [1.08360159, 1.08313   ],
       [1.08454025, 1.08204   ],
       [1.08555365, 1.08012   ],
       [1.07632375, 1.07556   ],
       [1.07671916, 1.07585   ],
       [1.07558668, 1.07292   ],
       [1.07407618, 1.07434   ],
       [1.07171261, 1.07465   ],
       [1.07463515, 1.07356   ],
       [1.07164156, 1.07684   ],
       [1.08080018, 1.07789   ],
       [1.07301152, 1.07107   ],
       [1.06994855, 1.07224   ],
       [1.07239163, 1.07328   ],
       [1.07168329, 1.07396   ],
       [1.07649481, 1.07869   ],
       [1.07989097, 1.0785    ],
       [1.07296407, 1.07515   ],
       [1.07336271, 1.079     ],
       [1.

In [285]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 68:69] + 127873)/10**5, yHigh)

0.953250402062488

In [286]:
x = dataset.iloc[:, 1:69].values
y = dataset.iloc[:,   69].values
y = y.reshape(len(y),1)
regressorLow = XGBRegressor(n_estimators=3000)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=3000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [287]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
temp = np.concatenate((testSet.iloc[:, 1:68].values, (yHigh*10**5 - 127873).reshape(len(yHigh), 1)), 1)
temp

array([[-17906.        , -17197.        , -18106.        , ...,
        -17920.        , -17911.        , -17716.02282333],
       [-17356.        , -17115.        , -18151.        , ...,
        -18463.        , -18229.        , -17965.86165237],
       [-17985.        , -17931.        , -18041.        , ...,
        -18459.        , -18047.        , -17817.81563568],
       ...,
       [-18318.        , -18288.        , -19430.        , ...,
        -15784.        , -15591.        , -14950.28385925],
       [-18831.        , -18803.        , -18895.        , ...,
        -16131.        , -15825.        , -15697.20158386],
       [-18809.        , -18673.        , -19000.        , ...,
        -16689.        , -16528.        , -16222.29466248]])

In [288]:
yLow = regressorLow.predict(temp)
yLow += 127873
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 69:70] + 127873)/10**5), 1)
tempLow

array([[1.09773076, 1.0941    ],
       [1.0938344 , 1.09414   ],
       [1.09351099, 1.09      ],
       [1.08815253, 1.08476   ],
       [1.08568859, 1.08453   ],
       [1.0811106 , 1.0848    ],
       [1.08444977, 1.0855    ],
       [1.08339393, 1.08102   ],
       [1.08245254, 1.07624   ],
       [1.07526028, 1.076     ],
       [1.07827675, 1.08043   ],
       [1.07819343, 1.07955   ],
       [1.0777787 , 1.07601   ],
       [1.07556093, 1.07421   ],
       [1.06992376, 1.07073   ],
       [1.06663883, 1.07018   ],
       [1.06780636, 1.07158   ],
       [1.06549287, 1.07054   ],
       [1.06365275, 1.06725   ],
       [1.06803238, 1.06352   ],
       [1.06296945, 1.06617   ],
       [1.07175922, 1.0705    ],
       [1.06637061, 1.06937   ],
       [1.06576085, 1.06744   ],
       [1.06477106, 1.06669   ],
       [1.06512511, 1.06682   ],
       [1.06300771, 1.07009   ],
       [1.07432473, 1.07428   ],
       [1.07122612, 1.07431   ],
       [1.0702883 , 1.0733    ],
       [1.

In [289]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 69:70] + 127873)/10**5, yLow)

0.9581946114232871

In [290]:
x = dataset.iloc[:, 1:70].values
y = dataset.iloc[:,   70].values
y = y.reshape(len(y),1)
regressorClose = XGBRegressor(n_estimators=2000)
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=2000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [291]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
temp = np.concatenate((testSet.iloc[:, 1:68].values, (yHigh*10**5 - 127873).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 127873).reshape(len(yLow), 1)), 1)
temp

array([[-17906.        , -17197.        , -18106.        , ...,
        -17911.        , -17716.02282333, -18099.9244194 ],
       [-17356.        , -17115.        , -18151.        , ...,
        -18229.        , -17965.86165237, -18489.5599823 ],
       [-17985.        , -17931.        , -18041.        , ...,
        -18047.        , -17817.81563568, -18521.90146255],
       ...,
       [-18318.        , -18288.        , -19430.        , ...,
        -15591.        , -14950.28385925, -15743.02563477],
       [-18831.        , -18803.        , -18895.        , ...,
        -15825.        , -15697.20158386, -16104.44435883],
       [-18809.        , -18673.        , -19000.        , ...,
        -16528.        , -16222.29466248, -17055.87754059]])

In [292]:
yClose = regressorClose.predict(temp)
yClose += 127873
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 70:71] + 127873)/10**5), 1)
tempClose

array([[1.10201573, 1.09645   ],
       [1.09564245, 1.09824   ],
       [1.09817755, 1.09122   ],
       [1.09130871, 1.08477   ],
       [1.08915067, 1.08527   ],
       [1.0856812 , 1.08735   ],
       [1.08961403, 1.08653   ],
       [1.08754516, 1.08378   ],
       [1.08333027, 1.07749   ],
       [1.07614934, 1.08019   ],
       [1.08377099, 1.08218   ],
       [1.08027422, 1.08104   ],
       [1.08073246, 1.07691   ],
       [1.07572341, 1.07555   ],
       [1.07091701, 1.07234   ],
       [1.07081544, 1.07227   ],
       [1.07009482, 1.07214   ],
       [1.06908572, 1.07067   ],
       [1.0637877 , 1.07316   ],
       [1.06971121, 1.06933   ],
       [1.06405425, 1.07604   ],
       [1.07585073, 1.07063   ],
       [1.07016528, 1.06967   ],
       [1.06793761, 1.07113   ],
       [1.06808245, 1.06984   ],
       [1.0678401 , 1.07069   ],
       [1.06397307, 1.07818   ],
       [1.07592309, 1.07456   ],
       [1.07086098, 1.07499   ],
       [1.07072055, 1.07622   ],
       [1.

In [293]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 70:71] + 127873)/10**5, yClose)

0.8943630358777315

In [294]:
y = test
classifierAscending = XGBClassifier(n_estimators=2000)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [295]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
openVal = testSet.iloc[:, 34].values
closeVal = testSet.iloc[:, 37].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1]

In [297]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
temp = np.concatenate((testSet.iloc[:, 1:68].values, (yHigh*10**5 - 127873).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 127873).reshape(len(yLow), 1)), 1)
yAscending = classifierAscending.predict(temp)
yAscending

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0])

In [298]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[27  9]
 [21  7]]


0.53125

In [300]:
yAscendingProb = classifierAscending.predict_proba(testSet.iloc[:, 1:70].values)
yAscendingProb

array([[7.32725561e-01, 2.67274439e-01],
       [4.34031010e-01, 5.65968990e-01],
       [9.91568327e-01, 8.43165815e-03],
       [9.98346925e-01, 1.65306136e-03],
       [9.47394311e-01, 5.26056662e-02],
       [4.95919645e-01, 5.04080355e-01],
       [6.82985544e-01, 3.17014486e-01],
       [8.03843379e-01, 1.96156651e-01],
       [9.93232846e-01, 6.76716445e-03],
       [1.64687932e-01, 8.35312068e-01],
       [5.16552925e-02, 9.48344707e-01],
       [9.84365702e-01, 1.56343114e-02],
       [9.46720898e-01, 5.32791093e-02],
       [1.55237317e-02, 9.84476268e-01],
       [9.13248658e-01, 8.67513493e-02],
       [8.77241731e-01, 1.22758284e-01],
       [2.11465836e-01, 7.88534164e-01],
       [8.29872251e-01, 1.70127779e-01],
       [7.88763165e-01, 2.11236864e-01],
       [9.88857985e-01, 1.11419857e-02],
       [9.12360370e-01, 8.76396298e-02],
       [9.95204985e-01, 4.79500787e-03],
       [9.54912424e-01, 4.50875461e-02],
       [9.99053001e-01, 9.47021064e-04],
       [9.598870