In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
dataset = pd.read_csv("1H.csv")
dataset = dataset.iloc[11:, :]*10**5 - 127868.5
openVal = dataset.iloc[:, 34]
closeVal = dataset.iloc[:, 37]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[  6471.5   6421.5   6461.5 ... -15469.5 -15526.5 -15526.5]
[  6411.5   6471.5   6481.5 ... -15526.5 -15527.5 -15565.5]
[0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 

In [3]:
x = dataset.iloc[:, 1:35].values
y = dataset.iloc[:,   35].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor(n_estimators=1500)
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [4]:
y = dataset.iloc[:, 36].values
y = y.reshape(len(y),1)
predHigh = regressorHigh.predict(x)
x = np.concatenate((x, predHigh.reshape(len(predHigh), 1)), 1)
regressorLow = XGBRegressor(n_estimators=1500)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [5]:
y = dataset.iloc[:, 37].values
y = y.reshape(len(y),1)
predLow = regressorLow.predict(x)
x = np.concatenate((x, predLow.reshape(len(predLow), 1)), 1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [6]:
y = test
classifierAscending = XGBClassifier(n_estimators=1500)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=1500, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [7]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
yHigh = regressorHigh.predict(testSet.iloc[:, 1:35].values)
yHigh += 127868.5
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 35:36] + 127868.5)/10**5), 1)
tempHigh

array([[1.12324393, 1.12345   ],
       [1.12336314, 1.12314   ],
       [1.1229105 , 1.12293   ],
       [1.12322521, 1.12297   ],
       [1.12340903, 1.12273   ],
       [1.12253606, 1.12279   ],
       [1.12342846, 1.12284   ],
       [1.12296903, 1.12275   ],
       [1.12292194, 1.12345   ],
       [1.12439287, 1.124     ],
       [1.1242466 , 1.12452   ],
       [1.12527514, 1.12488   ],
       [1.1247499 , 1.1245    ],
       [1.12498355, 1.12437   ],
       [1.12377417, 1.12377   ],
       [1.12371576, 1.12371   ],
       [1.12434947, 1.12359   ],
       [1.12297773, 1.12334   ],
       [1.1239692 , 1.1238    ],
       [1.12436604, 1.12383   ],
       [1.12362516, 1.12444   ],
       [1.12416613, 1.12442   ],
       [1.12477362, 1.12461   ],
       [1.12480855, 1.1244    ],
       [1.12339735, 1.1239    ],
       [1.12432563, 1.12401   ],
       [1.12412167, 1.12398   ],
       [1.12410831, 1.12464   ],
       [1.12480438, 1.12558   ],
       [1.12516224, 1.12488   ],
       [1.

In [8]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 35:36] + 127868.5)/10**5, yHigh)

0.9860288567774391

In [9]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
yLow = regressorLow.predict(testSet.iloc[:, 1:36].values)
yLow += 127868.5
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 36:37] + 127868.5)/10**5), 1)
tempLow

array([[1.12283742, 1.12195   ],
       [1.1225673 , 1.1224    ],
       [1.12223768, 1.12229   ],
       [1.12242854, 1.12232   ],
       [1.12194479, 1.12171   ],
       [1.12121582, 1.12145   ],
       [1.12158418, 1.12244   ],
       [1.12180328, 1.12224   ],
       [1.12248504, 1.12221   ],
       [1.12273049, 1.12226   ],
       [1.12300754, 1.12296   ],
       [1.12405252, 1.12365   ],
       [1.12315989, 1.12346   ],
       [1.1230551 , 1.12309   ],
       [1.12259221, 1.12292   ],
       [1.12302828, 1.12209   ],
       [1.12294352, 1.12033   ],
       [1.12135446, 1.12177   ],
       [1.12186515, 1.12254   ],
       [1.12341523, 1.12301   ],
       [1.12289047, 1.12322   ],
       [1.12353659, 1.12393   ],
       [1.12383652, 1.12413   ],
       [1.12405849, 1.12314   ],
       [1.12255931, 1.12308   ],
       [1.12332439, 1.12361   ],
       [1.12315035, 1.1237    ],
       [1.12347496, 1.12347   ],
       [1.12375736, 1.12385   ],
       [1.12343717, 1.12432   ],
       [1.

In [10]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 36:37] + 127868.5)/10**5, yLow)

0.9610973913347203

In [11]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
yClose = regressorClose.predict(testSet.iloc[:, 1:37].values)
yClose += 127868.5
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 37:38] + 127868.5)/10**5), 1)
tempClose

array([[1.12268591, 1.12289   ],
       [1.12268591, 1.1225    ],
       [1.12268591, 1.12269   ],
       [1.12268591, 1.12246   ],
       [1.12191129, 1.12177   ],
       [1.12179708, 1.12265   ],
       [1.12268591, 1.12265   ],
       [1.12191129, 1.1227    ],
       [1.12268591, 1.12326   ],
       [1.12268591, 1.12333   ],
       [1.12377119, 1.12449   ],
       [1.12439167, 1.1238    ],
       [1.12377119, 1.12435   ],
       [1.12377119, 1.12313   ],
       [1.12377119, 1.12339   ],
       [1.12268591, 1.12356   ],
       [1.12213635, 1.12213   ],
       [1.12268591, 1.12322   ],
       [1.12268591, 1.12352   ],
       [1.12377119, 1.1233    ],
       [1.12377119, 1.12405   ],
       [1.12377119, 1.12431   ],
       [1.12439167, 1.12439   ],
       [1.12377119, 1.12314   ],
       [1.12377119, 1.12361   ],
       [1.12377119, 1.12392   ],
       [1.12377119, 1.12375   ],
       [1.12439167, 1.12418   ],
       [1.12449265, 1.1245    ],
       [1.12439167, 1.12476   ],
       [1.

In [12]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 37:38] + 127868.5)/10**5, yClose)

0.9830169602098887

In [13]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
openVal = testSet.iloc[:, 34].values
closeVal = testSet.iloc[:, 37].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0]

In [14]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
yAscending = classifierAscending.predict(testSet.iloc[:, 1:37].values)
yAscending

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1])

In [15]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[43 11]
 [21 45]]


0.7333333333333333

In [16]:
yAscendingProb = classifierAscending.predict_proba(testSet.iloc[:, 1:37].values)
yAscendingProb

array([[0.866975  , 0.13302498],
       [0.5633768 , 0.4366232 ],
       [0.17999321, 0.8200068 ],
       [0.26454347, 0.7354565 ],
       [0.6970856 , 0.3029144 ],
       [0.5375111 , 0.46248886],
       [0.33602095, 0.66397905],
       [0.4322515 , 0.5677485 ],
       [0.33294916, 0.66705084],
       [0.58870167, 0.41129833],
       [0.11684591, 0.8831541 ],
       [0.780203  , 0.21979703],
       [0.32014793, 0.67985207],
       [0.7903081 , 0.2096919 ],
       [0.19574773, 0.80425227],
       [0.96400464, 0.03599538],
       [0.99354476, 0.00645526],
       [0.13232994, 0.86767006],
       [0.2948845 , 0.7051155 ],
       [0.6183239 , 0.38167608],
       [0.19637942, 0.8036206 ],
       [0.7901761 , 0.20982389],
       [0.6552291 , 0.34477088],
       [0.8487071 , 0.15129292],
       [0.07373762, 0.9262624 ],
       [0.35808188, 0.6419181 ],
       [0.72957516, 0.27042484],
       [0.06058604, 0.93941396],
       [0.01560599, 0.984394  ],
       [0.5690762 , 0.43092382],
       [0.