In [56]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [57]:
dataset = pd.read_csv("1H.csv")
dataset = dataset.iloc[11:, :]*10**5 - 127868.5
openVal = dataset.iloc[:, 34]
closeVal = dataset.iloc[:, 37]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[  6471.5   6421.5   6461.5 ... -15469.5 -15526.5 -15526.5]
[  6411.5   6471.5   6481.5 ... -15526.5 -15527.5 -15565.5]
[0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 

In [58]:
x = dataset.iloc[:, 1:35].values
y = dataset.iloc[:,   35].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor(n_estimators=1500)
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [59]:
y = dataset.iloc[:, 36].values
y = y.reshape(len(y),1)
predHigh = regressorHigh.predict(x)
x = np.concatenate((x, predHigh.reshape(len(predHigh), 1)), 1)
regressorLow = XGBRegressor(n_estimators=1500)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [60]:
y = dataset.iloc[:, 37].values
y = y.reshape(len(y),1)
predLow = regressorLow.predict(x)
x = np.concatenate((x, predLow.reshape(len(predLow), 1)), 1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [61]:
y = test
classifierAscending = XGBClassifier(n_estimators=1500)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=1500, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [62]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yHigh = regressorHigh.predict(testSet.iloc[:, 1:35].values)
yHigh += 127873
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 35:36] + 127873)/10**5), 1)
tempHigh

array([[1.12328887, 1.12345   ],
       [1.12342668, 1.12314   ],
       [1.12331724, 1.12293   ],
       [1.12327015, 1.12297   ],
       [1.12272692, 1.12273   ],
       [1.12258112, 1.12279   ],
       [1.12347341, 1.12284   ],
       [1.12301409, 1.12275   ],
       [1.12297797, 1.12345   ],
       [1.12383831, 1.124     ],
       [1.12408519, 1.12452   ],
       [1.1251266 , 1.12488   ],
       [1.12479484, 1.1245    ],
       [1.1247344 , 1.12437   ],
       [1.12381923, 1.12377   ],
       [1.12377167, 1.12371   ],
       [1.12415063, 1.12359   ],
       [1.12276351, 1.12334   ],
       [1.12404919, 1.1238    ],
       [1.12439585, 1.12383   ],
       [1.12375295, 1.12444   ],
       [1.12435961, 1.12442   ],
       [1.12462044, 1.12461   ],
       [1.12493312, 1.1244    ],
       [1.123523  , 1.1239    ],
       [1.12437057, 1.12401   ],
       [1.12416661, 1.12398   ],
       [1.12413323, 1.12464   ],
       [1.12482131, 1.12558   ],
       [1.12523139, 1.12488   ],
       [1.

In [63]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 35:36] + 127873)/10**5, yHigh)

0.9863244962054809

In [64]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yLow = regressorLow.predict(testSet.iloc[:, 1:36].values)
yLow += 127873
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 36:37] + 127873)/10**5), 1)
tempLow

array([[1.12282681, 1.12195   ],
       [1.12253666, 1.1224    ],
       [1.12230384, 1.12229   ],
       [1.12256432, 1.12232   ],
       [1.12198997, 1.12171   ],
       [1.12126088, 1.12145   ],
       [1.12147427, 1.12244   ],
       [1.12184823, 1.12224   ],
       [1.12258875, 1.12221   ],
       [1.12291825, 1.12226   ],
       [1.12313509, 1.12296   ],
       [1.12409747, 1.12365   ],
       [1.12302744, 1.12346   ],
       [1.1231221 , 1.12309   ],
       [1.12256455, 1.12292   ],
       [1.12282407, 1.12209   ],
       [1.1219784 , 1.12033   ],
       [1.12145436, 1.12177   ],
       [1.12174928, 1.12254   ],
       [1.12275052, 1.12301   ],
       [1.12312949, 1.12322   ],
       [1.12347996, 1.12393   ],
       [1.12388158, 1.12413   ],
       [1.12410343, 1.12314   ],
       [1.12290406, 1.12308   ],
       [1.12338102, 1.12361   ],
       [1.12316322, 1.1237    ],
       [1.12358832, 1.12347   ],
       [1.12344348, 1.12385   ],
       [1.12348223, 1.12432   ],
       [1.

In [65]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 36:37] + 127873)/10**5, yLow)

0.9620463416776638

In [66]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yClose = regressorClose.predict(testSet.iloc[:, 1:37].values)
yClose += 127873
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 37:38] + 127873)/10**5), 1)
tempClose

array([[1.12273097, 1.12289   ],
       [1.12273097, 1.1225    ],
       [1.12273097, 1.12269   ],
       [1.12273097, 1.12246   ],
       [1.12195635, 1.12177   ],
       [1.12184203, 1.12265   ],
       [1.12195635, 1.12265   ],
       [1.12195635, 1.1227    ],
       [1.12273097, 1.12326   ],
       [1.12273097, 1.12333   ],
       [1.12381613, 1.12449   ],
       [1.12443674, 1.1238    ],
       [1.12381613, 1.12435   ],
       [1.12381613, 1.12313   ],
       [1.12381613, 1.12339   ],
       [1.12273097, 1.12356   ],
       [1.12218142, 1.12213   ],
       [1.12273097, 1.12322   ],
       [1.12273097, 1.12352   ],
       [1.12381613, 1.1233    ],
       [1.12381613, 1.12405   ],
       [1.12381613, 1.12431   ],
       [1.12443674, 1.12439   ],
       [1.12381613, 1.12314   ],
       [1.12381613, 1.12361   ],
       [1.12381613, 1.12392   ],
       [1.12381613, 1.12375   ],
       [1.12443674, 1.12418   ],
       [1.12453771, 1.1245    ],
       [1.12443674, 1.12476   ],
       [1.

In [67]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 37:38] + 127873)/10**5, yClose)

0.9835668294404093

In [68]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
openVal = testSet.iloc[:, 34].values
closeVal = testSet.iloc[:, 37].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0]

In [69]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127873
yAscending = classifierAscending.predict(testSet.iloc[:, 1:37].values)
yAscending

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1])

In [70]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[41 13]
 [19 47]]


0.7333333333333333

In [71]:
yAscendingProb = classifierAscending.predict_proba(testSet.iloc[:, 1:37].values)
yAscendingProb

array([[0.87756276, 0.12243725],
       [0.5164335 , 0.4835665 ],
       [0.19713199, 0.802868  ],
       [0.26454347, 0.7354565 ],
       [0.7473699 , 0.25263014],
       [0.49879622, 0.5012038 ],
       [0.29686373, 0.70313627],
       [0.46493876, 0.53506124],
       [0.33294916, 0.66705084],
       [0.7393409 , 0.26065907],
       [0.09670442, 0.9032956 ],
       [0.79241365, 0.20758636],
       [0.61124617, 0.38875383],
       [0.9388655 , 0.06113449],
       [0.24572647, 0.75427353],
       [0.9428986 , 0.05710141],
       [0.99460435, 0.00539567],
       [0.13232994, 0.86767006],
       [0.2948845 , 0.7051155 ],
       [0.6591879 , 0.3408121 ],
       [0.24268478, 0.7573152 ],
       [0.67069674, 0.3293033 ],
       [0.5505407 , 0.4494593 ],
       [0.86362743, 0.1363726 ],
       [0.07373762, 0.9262624 ],
       [0.35808188, 0.6419181 ],
       [0.39200932, 0.6079907 ],
       [0.12360871, 0.8763913 ],
       [0.01881313, 0.98118687],
       [0.48281044, 0.51718956],
       [0.