In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [28]:
dataset = pd.read_csv("1H.csv")
dataset = dataset.iloc[22:, :]*10**5 - 127868.5
openVal = dataset.iloc[:, 67]
closeVal = dataset.iloc[:, 70]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[  6591.5   6601.5   6621.5 ... -15654.5 -15546.5 -15514.5]
[  6551.5   6631.5   6601.5 ... -15546.5 -15516.5 -15538.5]
[0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 

In [29]:
x = dataset.iloc[:, 1:68].values
y = dataset.iloc[:,   68].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor()
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [30]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
yHigh = regressorHigh.predict(testSet.iloc[:, 1:68].values)
yHigh += 127868.5
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 68:69] + 127868.5)/10**5), 1)
tempHigh

array([[1.12389076, 1.12444   ],
       [1.12479889, 1.12442   ],
       [1.12497115, 1.12461   ],
       [1.12497115, 1.1244    ],
       [1.12389076, 1.1239    ],
       [1.12389076, 1.12401   ],
       [1.12479889, 1.12398   ],
       [1.12479889, 1.12464   ],
       [1.124946  , 1.12558   ],
       [1.12511826, 1.12488   ],
       [1.12522137, 1.12547   ],
       [1.12669027, 1.12564   ],
       [1.12522137, 1.12641   ],
       [1.12522137, 1.12573   ],
       [1.12656188, 1.12758   ],
       [1.12702394, 1.1256    ],
       [1.124946  , 1.12494   ],
       [1.12541842, 1.12601   ],
       [1.12656188, 1.12578   ],
       [1.12656188, 1.12698   ],
       [1.12526834, 1.1246    ],
       [1.12389076, 1.12402   ],
       [1.1250571 , 1.12455   ],
       [1.12306881, 1.12285   ],
       [1.1220578 , 1.12211   ],
       [1.12258267, 1.12311   ],
       [1.12340462, 1.12308   ],
       [1.12340462, 1.12315   ],
       [1.12340462, 1.12294   ],
       [1.12340462, 1.12326   ],
       [1.

In [31]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 68:69] + 127873)/10**5, yHigh)

0.984174450380018

In [32]:
x = dataset.iloc[:, 1:69].values
y = dataset.iloc[:,   69].values
y = y.reshape(len(y),1)
regressorLow = XGBRegressor(n_estimators=2000)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=2000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [33]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
temp = np.concatenate((testSet.iloc[:, 1:68].values, (yHigh*10**5 - 127868.5).reshape(len(yHigh), 1)), 1)
temp

array([[-15526.5       , -15501.5       , -15554.5       , ...,
        -15567.5       , -15538.5       , -15479.42424393],
       [-15526.5       , -15526.5       , -15566.5       , ...,
        -15546.5       , -15463.5       , -15388.61060715],
       [-15580.5       , -15523.5       , -15673.5       , ...,
        -15475.5       , -15437.5       , -15371.38486481],
       ...,
       [-16548.5       , -16546.5       , -16585.5       , ...,
        -16639.5       , -16608.5       , -16514.81652832],
       [-16577.5       , -16525.5       , -16634.5       , ...,
        -16627.5       , -16620.5       , -16514.81652832],
       [-16526.5       , -16503.5       , -16558.5       , ...,
        -16676.5       , -16614.5       , -16487.38647079]])

In [34]:
yLow = regressorLow.predict(temp)
yLow += 127868.5
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 69:70] + 127868.5)/10**5), 1)
tempLow

array([[1.12293255, 1.12322   ],
       [1.12346172, 1.12393   ],
       [1.12391651, 1.12413   ],
       [1.12414169, 1.12314   ],
       [1.12304926, 1.12308   ],
       [1.12341416, 1.12361   ],
       [1.12383437, 1.1237    ],
       [1.12370527, 1.12347   ],
       [1.12386107, 1.12385   ],
       [1.12388635, 1.12432   ],
       [1.12406516, 1.12445   ],
       [1.12515283, 1.12503   ],
       [1.12438452, 1.12495   ],
       [1.12338972, 1.12404   ],
       [1.12503779, 1.12432   ],
       [1.1253202 , 1.12281   ],
       [1.12370789, 1.1237    ],
       [1.12426591, 1.1247    ],
       [1.12505913, 1.12419   ],
       [1.12518823, 1.12231   ],
       [1.12375617, 1.12168   ],
       [1.12156308, 1.12251   ],
       [1.12296247, 1.12212   ],
       [1.12158918, 1.12089   ],
       [1.11967552, 1.12094   ],
       [1.11986482, 1.12138   ],
       [1.12216246, 1.12244   ],
       [1.12278724, 1.12265   ],
       [1.12241209, 1.12232   ],
       [1.12258255, 1.12259   ],
       [1.

In [35]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 69:70] + 127873)/10**5, yLow)

0.9581671802811765

In [36]:
x = dataset.iloc[:, 1:70].values
y = dataset.iloc[:,   70].values
y = y.reshape(len(y),1)
regressorClose = XGBRegressor()
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [37]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
temp = np.concatenate((testSet.iloc[:, 1:68].values, (yHigh*10**5 - 127868.5).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 127868.5).reshape(len(yLow), 1)), 1)
temp

array([[-15526.5       , -15501.5       , -15554.5       , ...,
        -15538.5       , -15479.42424393, -15575.24467087],
       [-15526.5       , -15526.5       , -15566.5       , ...,
        -15463.5       , -15388.61060715, -15522.32766724],
       [-15580.5       , -15523.5       , -15673.5       , ...,
        -15437.5       , -15371.38486481, -15476.84932327],
       ...,
       [-16548.5       , -16546.5       , -16585.5       , ...,
        -16608.5       , -16514.81652832, -16641.69097519],
       [-16577.5       , -16525.5       , -16634.5       , ...,
        -16620.5       , -16514.81652832, -16656.44908524],
       [-16526.5       , -16503.5       , -16558.5       , ...,
        -16614.5       , -16487.38647079, -16661.86118698]])

In [38]:
yClose = regressorClose.predict(temp)
yClose += 127868.5
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 70:71] + 127868.5)/10**5), 1)
tempClose

array([[1.12290359, 1.12405   ],
       [1.12421799, 1.12431   ],
       [1.12426221, 1.12439   ],
       [1.12426221, 1.12314   ],
       [1.12290359, 1.12361   ],
       [1.12397277, 1.12392   ],
       [1.12426221, 1.12375   ],
       [1.12421799, 1.12418   ],
       [1.12426221, 1.1245    ],
       [1.12426221, 1.12476   ],
       [1.12426221, 1.12538   ],
       [1.12600279, 1.12518   ],
       [1.12426221, 1.12502   ],
       [1.12421799, 1.12563   ],
       [1.12593985, 1.12539   ],
       [1.12600279, 1.12369   ],
       [1.12421799, 1.12488   ],
       [1.12426221, 1.12573   ],
       [1.12593985, 1.12534   ],
       [1.12593985, 1.12397   ],
       [1.12426221, 1.12266   ],
       [1.12283099, 1.12369   ],
       [1.12314606, 1.12226   ],
       [1.12283099, 1.12148   ],
       [1.12087941, 1.12189   ],
       [1.12125182, 1.1229    ],
       [1.12290359, 1.12301   ],
       [1.12290359, 1.1228    ],
       [1.12290359, 1.12267   ],
       [1.12290359, 1.12314   ],
       [1.

In [39]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 70:71] + 127873)/10**5, yClose)

0.9579459527011388

In [40]:
y = test
classifierAscending = XGBClassifier(n_estimators=2000)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [41]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
openVal = testSet.iloc[:, 67].values
closeVal = testSet.iloc[:, 70].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0]

In [42]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 127868.5
temp = np.concatenate((testSet.iloc[:, 1:68].values, (yHigh*10**5 - 127868.5).reshape(len(yHigh), 1)), 1)
temp = np.concatenate((temp, (yLow*10**5 - 127868.5).reshape(len(yLow), 1)), 1)
yAscending = classifierAscending.predict(temp)
yAscending

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1])

In [43]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[18 29]
 [18 35]]


0.53

In [44]:
yAscendingProb = classifierAscending.predict_proba(testSet.iloc[:, 1:70].values)
yAscendingProb

array([[0.07464826, 0.92535174],
       [0.14267796, 0.85732204],
       [0.36488515, 0.63511485],
       [0.97664636, 0.02335361],
       [0.05465573, 0.94534427],
       [0.09060675, 0.90939325],
       [0.6249734 , 0.37502655],
       [0.09715658, 0.9028434 ],
       [0.1058352 , 0.8941648 ],
       [0.29009515, 0.70990485],
       [0.1996659 , 0.8003341 ],
       [0.47805083, 0.5219492 ],
       [0.06480098, 0.935199  ],
       [0.2778495 , 0.7221505 ],
       [0.08262533, 0.9173747 ],
       [0.99125123, 0.00874879],
       [0.01609576, 0.98390424],
       [0.01527643, 0.98472357],
       [0.9920889 , 0.00791107],
       [0.8681287 , 0.13187127],
       [0.9963438 , 0.00365619],
       [0.08701921, 0.9129808 ],
       [0.8316552 , 0.1683448 ],
       [0.98518413, 0.01481588],
       [0.90738595, 0.09261408],
       [0.23750186, 0.76249814],
       [0.48416632, 0.5158337 ],
       [0.7299293 , 0.27007067],
       [0.43883216, 0.56116784],
       [0.1312818 , 0.8687182 ],
       [0.