In [76]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [77]:
dataset = pd.read_csv("12H.csv")
dataset = dataset.iloc[11:, :]*10**5 - 121325
openVal = dataset.iloc[:, 34]
closeVal = dataset.iloc[:, 37]
openVal = openVal
closeVal = closeVal
openVal = openVal.values
closeVal = closeVal.values
test = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        test.append(0)
    else:
        test.append(1)
print(openVal)
print(closeVal)
print(test)

[-18875. -18795. -18335. ... -14453. -13708. -13583.]
[-18815. -18315. -17965. ... -13710. -13582. -14265.]
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 

In [78]:
x = dataset.iloc[:, 1:35].values
y = dataset.iloc[:,   35].values
y = y.reshape(len(y),1)
regressorHigh = XGBRegressor(n_estimators=3000, max_leaves=0)
regressorHigh.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=0,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=3000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [79]:
y = dataset.iloc[:, 36].values
y = y.reshape(len(y),1)
predHigh = regressorHigh.predict(x)
x = np.concatenate((x, predHigh.reshape(len(predHigh), 1)), 1)
regressorLow = XGBRegressor(n_estimators=1500, max_leaves=0)
regressorLow.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=0,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [80]:
y = dataset.iloc[:, 37].values
y = y.reshape(len(y),1)
predLow = regressorLow.predict(x)
x = np.concatenate((x, predLow.reshape(len(predLow), 1)), 1)
regressorClose = XGBRegressor(n_estimators=2000, max_leaves=0)
regressorClose.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=0,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=2000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [81]:
y = test
classifierAscending = XGBClassifier(n_estimators=3000, max_leaves=0)
classifierAscending.fit(x, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=0,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=3000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [82]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 121325
yHigh = regressorHigh.predict(testSet.iloc[:, 1:35].values)
yHigh += 121325
yHigh /= 10**5
tempHigh = np.concatenate((yHigh.reshape(len(yHigh), 1), (testSet.iloc[:, 35:36] + 121325)/10**5), 1)
tempHigh

array([[1.07256806, 1.07091   ],
       [1.07162237, 1.07225   ],
       [1.07381737, 1.07329   ],
       [1.07269692, 1.07011   ],
       [1.07324016, 1.07044   ],
       [1.07386231, 1.07398   ],
       [1.07242692, 1.073     ],
       [1.07555509, 1.07871   ],
       [1.07978213, 1.07851   ],
       [1.07872677, 1.07842   ],
       [1.07563448, 1.0784    ],
       [1.07918584, 1.07902   ],
       [1.07871306, 1.08083   ],
       [1.08217394, 1.08236   ],
       [1.08299005, 1.08048   ],
       [1.08271253, 1.0864    ],
       [1.08784735, 1.08444   ],
       [1.08676207, 1.09528   ],
       [1.09721589, 1.09625   ],
       [1.09877062, 1.09706   ],
       [1.09387076, 1.09463   ],
       [1.09654009, 1.09297   ],
       [1.09459114, 1.09463   ],
       [1.09722173, 1.09401   ],
       [1.09269893, 1.09338   ],
       [1.09296203, 1.09908   ],
       [1.09846735, 1.10038   ],
       [1.10293031, 1.10122   ],
       [1.10101402, 1.09586   ],
       [1.0860244 , 1.09029   ],
       [1.

In [83]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 35:36] + 121325)/10**5, yHigh)

0.961428985070312

In [84]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 121325
yLow = regressorLow.predict(testSet.iloc[:, 1:36].values)
yLow += 121325
yLow /= 10**5
tempLow = np.concatenate((yLow.reshape(len(yLow), 1), (testSet.iloc[:, 36:37] + 121325)/10**5), 1)
tempLow

array([[1.06826246, 1.06834   ],
       [1.06570363, 1.06747   ],
       [1.06742036, 1.06951   ],
       [1.0650022 , 1.06671   ],
       [1.06462777, 1.06683   ],
       [1.06544197, 1.06902   ],
       [1.06857014, 1.06913   ],
       [1.06745958, 1.07209   ],
       [1.07348192, 1.07593   ],
       [1.0732528 , 1.0743    ],
       [1.07332277, 1.0733    ],
       [1.07251239, 1.07431   ],
       [1.07392001, 1.07509   ],
       [1.07585824, 1.0778    ],
       [1.07527685, 1.0774    ],
       [1.07859755, 1.07965   ],
       [1.08066249, 1.08039   ],
       [1.08296967, 1.08146   ],
       [1.09099925, 1.09339   ],
       [1.09180558, 1.09176   ],
       [1.09017384, 1.09252   ],
       [1.08647442, 1.09073   ],
       [1.08907354, 1.09105   ],
       [1.08986938, 1.08918   ],
       [1.08673513, 1.09056   ],
       [1.09036362, 1.09082   ],
       [1.09430182, 1.09797   ],
       [1.09535027, 1.09486   ],
       [1.09269345, 1.08487   ],
       [1.07924211, 1.08444   ],
       [1.

In [85]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 36:37] + 121325)/10**5, yLow)

0.9762635378100072

In [86]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 121325
yClose = regressorClose.predict(testSet.iloc[:, 1:37].values)
yClose += 121325
yClose /= 10**5
tempClose = np.concatenate((yClose.reshape(len(yClose), 1), (testSet.iloc[:, 37:38] + 121325)/10**5), 1)
tempClose

array([[1.07209313, 1.06961   ],
       [1.06968713, 1.07125   ],
       [1.07173395, 1.06993   ],
       [1.06726146, 1.06923   ],
       [1.0706048 , 1.06931   ],
       [1.07186794, 1.06982   ],
       [1.071612  , 1.07268   ],
       [1.07696807, 1.07814   ],
       [1.07932878, 1.07634   ],
       [1.07531345, 1.07495   ],
       [1.07684362, 1.07771   ],
       [1.07391894, 1.07579   ],
       [1.08189213, 1.08073   ],
       [1.07962418, 1.07925   ],
       [1.08060825, 1.08021   ],
       [1.08267987, 1.08308   ],
       [1.08196449, 1.08329   ],
       [1.08825362, 1.09454   ],
       [1.09359264, 1.09505   ],
       [1.09435678, 1.09406   ],
       [1.09304047, 1.09295   ],
       [1.09168363, 1.09225   ],
       [1.09262192, 1.0938    ],
       [1.09132707, 1.09178   ],
       [1.09189236, 1.0925    ],
       [1.09609425, 1.09856   ],
       [1.09820664, 1.0993    ],
       [1.09758222, 1.09551   ],
       [1.08749747, 1.08492   ],
       [1.08488262, 1.08898   ],
       [1.

In [87]:
from sklearn.metrics import r2_score
r2_score((testSet.iloc[:, 37:38] + 121325)/10**5, yClose)

0.9859184417050646

In [88]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 121325
openVal = testSet.iloc[:, 34].values
closeVal = testSet.iloc[:, 37].values
ascending = []
for i in range(len(openVal)):
    if closeVal[i] - openVal[i] < 0:
        ascending.append(0)
    else:
        ascending.append(1)
ascending

[0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0]

In [89]:
testSet = pd.read_csv('test.csv')
testSet = testSet.iloc[:, :]*10**5 - 121325
yAscending = classifierAscending.predict(testSet.iloc[:, 1:37].values)
yAscending

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0])

In [90]:
cm = confusion_matrix(ascending, yAscending)
print(cm)
accuracy_score(ascending, yAscending)

[[25  4]
 [11 30]]


0.7857142857142857

In [91]:
yAscendingProb = classifierAscending.predict_proba(testSet.iloc[:, 1:37].values)
yAscendingProb

array([[6.3327330e-01, 3.6672670e-01],
       [7.0586360e-01, 2.9413643e-01],
       [8.0338895e-01, 1.9661103e-01],
       [9.2401040e-01, 7.5989574e-02],
       [5.9754062e-01, 4.0245941e-01],
       [6.3210249e-01, 3.6789751e-01],
       [7.9813784e-01, 2.0186216e-01],
       [1.9109845e-03, 9.9808902e-01],
       [7.1104705e-02, 9.2889529e-01],
       [9.8192203e-01, 1.8077988e-02],
       [7.9485416e-02, 9.2051458e-01],
       [9.9005300e-01, 9.9469982e-03],
       [2.1871328e-03, 9.9781287e-01],
       [9.8208523e-01, 1.7914778e-02],
       [8.9231652e-01, 1.0768349e-01],
       [2.2022605e-02, 9.7797740e-01],
       [5.9099787e-01, 4.0900213e-01],
       [1.0424852e-03, 9.9895751e-01],
       [2.6807493e-01, 7.3192507e-01],
       [8.4114015e-02, 9.1588598e-01],
       [4.7623676e-01, 5.2376324e-01],
       [3.3741552e-01, 6.6258448e-01],
       [1.9324982e-01, 8.0675018e-01],
       [9.9932867e-01, 6.7135558e-04],
       [7.2307253e-01, 2.7692750e-01],
       [1.0027301e-01, 8.